/* =========================================================
Nombre completo: bdl.v2.mirror.js
Ruta o ubicación: /BDLocal/patches/bdl.v2.mirror.js
Función o funciones:
- Espejar datos legacy hacia tablas V2 sin borrar información existente.
- Consolidar Telegram en personas y contactos_estudiante.
- Usar cedula__periodoId como clave local única.
- Ignorar IDs antiguos invertidos al construir registros V2.
- Exponer actualización local de Telegram mediante BL2Core.
========================================================= */
(function(window){
  "use strict";

  var VERSION="1.2.0-canonical-local-id";
  var FLAG="__bdlV2MirrorInstalled";
  if(window[FLAG]){return;}
  window[FLAG]=true;

  function text(value){return String(value==null?"":value).trim();}
  function now(){return new Date().toISOString();}
  function clone(value){try{return JSON.parse(JSON.stringify(value));}catch(error){return value;}}
  function normalizeCedula(value){
    var rules=window.BDLRulesPersona;
    if(rules&&typeof rules.normalizeCedula==="function"){return rules.normalizeCedula(value);}
    var utils=window.BL2Config&&window.BL2Config.utils;
    return utils&&typeof utils.normalizeCedula==="function"?utils.normalizeCedula(value):text(value).replace(/[^0-9A-Za-z]/g,"").toUpperCase();
  }
  function period(value){value=text(value);var match=value.match(/^(\d{4})-(\d{2})_+(\d{4})-(\d{2})$/);return match?match[1]+"-"+match[2]+"__"+match[3]+"-"+match[4]:value.replace(/_+/g,"__");}
  function studentIdFrom(row){var cedula=normalizeCedula(row&& (row.cedula||row.numeroIdentificacion||row.NumeroIdentificacion)),periodoId=period(row&&(row.periodoId||row.periodId||row.ultimoPeriodoId));return cedula&&periodoId?cedula+"__"+periodoId:"";}
  function key(value){return text(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"");}
  function first(row,names){row=row||{};for(var i=0;i<names.length;i+=1){if(text(row[names[i]])){return row[names[i]];}}return "";}
  function user(value){var rules=window.BDLRulesPersona;return rules&&rules.normalizeTelegramUser?rules.normalizeTelegramUser(value):text(value).replace(/^@+/,"").replace(/\s+/g,"");}
  function chat(value){var rules=window.BDLRulesPersona;return rules&&rules.normalizeTelegramChatId?rules.normalizeTelegramChatId(value):text(value).replace(/\s+/g,"");}
  function telegram(row){return {telegramUser:user(first(row,["telegramUser","_telegramUser","telegramUsername","usuarioTelegram","telegram","Telegram"])),telegramChatId:chat(first(row,["telegramChatId","_telegramChatId","chatIdTelegram","telegramChatID","chatId"])),telegramUpdatedAt:text(first(row,["telegramUpdatedAt","telegramActualizadoEn"])),telegramSource:text(first(row,["telegramSource","origenTelegram"])),telegramCheckedAt:text(first(row,["telegramCheckedAt","telegramRevisadoEn"])),telegramVerifiedAt:text(first(row,["telegramVerifiedAt","telegramVerificadoEn"]))};}
  function stores(){var s=window.BL2Config&&window.BL2Config.stores||{};return {estudiantes:s.estudiantes||"estudiantes",requisitos:s.requisitos||"requisitos",contactos:s.contactos||"contactos",notas:s.notas||"notas",periodos:s.periodos||"periodos",personas:s.personas||"personas",matriculas:s.matriculasPeriodo||"matriculas_periodo",requisitosV2:s.requisitosEstudiante||"requisitos_estudiante",contactosV2:s.contactosEstudiante||"contactos_estudiante",notasV2:s.notasTitulacion||"notas_titulacion",divisiones:s.divisionesEstudiante||"divisiones_estudiante",periodosCarreras:s.periodosCarreras||"periodos_carreras",periodosDivisiones:s.periodosDivisiones||"periodos_divisiones"};}
  function merge(existing,incoming){existing=existing||{};incoming=incoming||{};var output=Object.assign({},existing);Object.keys(incoming).forEach(function(name){var value=incoming[name];if(value===undefined||value===null||text(value)===""){if(output[name]===undefined){output[name]=value;}}else{output[name]=clone(value);}});output.createdAt=existing.createdAt||incoming.createdAt||now();output.updatedAt=text(incoming.updatedAt||existing.updatedAt)||now();return output;}
  function primaryKey(storeName,row,s){if(storeName===s.personas){return row.cedula;}if(storeName===s.matriculas||storeName===s.notasV2){return row.idEstudiantePeriodo||row.id;}return row.id||row.idEstudiantePeriodo||row.cedula;}
  function mergedPut(storeName,rows,originalBulkPut){rows=(rows||[]).filter(Boolean);if(!rows.length){return Promise.resolve([]);}var current=window.BL2DB,s=stores();if(!current||!current.get){return originalBulkPut(storeName,rows);}return Promise.all(rows.map(function(row){var primary=primaryKey(storeName,row,s);return !text(primary)?row:current.get(storeName,primary).catch(function(){return null;}).then(function(existing){return merge(existing,row);});})).then(function(output){return originalBulkPut(storeName,output);});}

  function persona(row){var cedula=normalizeCedula(row.cedula||row.numeroIdentificacion||row.NumeroIdentificacion);if(!cedula){return null;}var base=window.BDLRulesPersona&&window.BDLRulesPersona.buildPersona?window.BDLRulesPersona.buildPersona(row):{},tg=telegram(row);return Object.assign({cedula:cedula,numeroIdentificacion:cedula,nombreCompleto:text(row.Nombres||row.nombres||row.Nombre||row.nombre),nombres:text(row.Nombres||row.nombres||row.Nombre||row.nombre),correoPersonal:text(row.CorreoPersonal||row.correoPersonal),correoInstitucional:text(row.CorreoInstitucional||row.correoInstitucional),celular:text(row.Celular||row.celular),source:"v2_mirror",updatedAt:text(row.updatedAt)||now()},base,tg,{cedula:cedula,numeroIdentificacion:cedula,_telegramUser:tg.telegramUser,_telegramChatId:tg.telegramChatId});}
  function matricula(row){var id=studentIdFrom(row),cedula=normalizeCedula(row.cedula||row.numeroIdentificacion),periodoId=period(row.periodoId||row.periodId||row.ultimoPeriodoId);if(!id){return null;}return {id:id,idEstudiantePeriodo:id,studentId:id,cedula:cedula,numeroIdentificacion:cedula,periodoId:periodoId,periodId:periodoId,periodoLabel:text(row.periodoLabel||periodoId),carrera:text(row.NombreCarrera||row.nombreCarrera||row.Carrera||row.carrera),codigoCarrera:text(row.CodigoCarrera||row.codigoCarrera),division:text(row.division||row._division),estadoMatricula:text(row.estadoMatricula||"ACTIVO").toUpperCase()==="RETIRADO"?"RETIRADO":"ACTIVO",sede:text(row.Sede||row.sede),horarioComplexivo:text(row.HorarioComplexivo||row.horarioComplexivo),source:"v2_mirror",updatedAt:text(row.updatedAt)||now()};}
  function contacto(row){var id=studentIdFrom(row),cedula=normalizeCedula(row.cedula||row.numeroIdentificacion),periodoId=period(row.periodoId||row.periodId||row.ultimoPeriodoId);if(!id){return null;}var tg=telegram(row);return Object.assign({id:id,idEstudiantePeriodo:id,studentId:id,cedula:cedula,numeroIdentificacion:cedula,periodoId:periodoId,periodId:periodoId,periodoLabel:text(row.periodoLabel||periodoId),CorreoPersonal:text(row.CorreoPersonal||row.correoPersonal),CorreoInstitucional:text(row.CorreoInstitucional||row.correoInstitucional),Celular:text(row.Celular||row.celular),correoPersonal:text(row.CorreoPersonal||row.correoPersonal),correoInstitucional:text(row.CorreoInstitucional||row.correoInstitucional),celular:text(row.Celular||row.celular),source:"v2_mirror",updatedAt:text(row.updatedAt)||now()},tg,{_telegramUser:tg.telegramUser,_telegramChatId:tg.telegramChatId});}
  function division(row){var id=studentIdFrom(row),label=text(row.division||row._division);if(!id||!label){return null;}return {id:id+"__"+key(label),idEstudiantePeriodo:id,studentId:id,cedula:normalizeCedula(row.cedula||row.numeroIdentificacion),periodoId:period(row.periodoId||row.periodId),division:label,divisionKey:key(label),source:"v2_mirror",updatedAt:text(row.updatedAt)||now()};}
  function requisito(row){var id=studentIdFrom(row),requisitoKey=key(row.key||row.nombre||row.requisitoKey);if(!id||!requisitoKey){return null;}return Object.assign({},row,{id:id+"__"+requisitoKey,idEstudiantePeriodo:id,studentId:id,cedula:normalizeCedula(row.cedula),numeroIdentificacion:normalizeCedula(row.cedula),periodoId:period(row.periodoId),requisitoKey:requisitoKey,estado:text(row.estado||row.valor||row.value),source:"v2_mirror",updatedAt:text(row.updatedAt)||now()});}
  function legacyContact(row){var id=studentIdFrom(row);if(!id){return null;}var tg=telegram(row),cedula=normalizeCedula(row.cedula||row.numeroIdentificacion),periodoId=period(row.periodoId||row.periodId);return Object.assign({},row,{id:id,idEstudiantePeriodo:id,studentId:id,cedula:cedula,numeroIdentificacion:cedula,periodoId:periodoId,correoPersonal:text(row.correoPersonal||row.CorreoPersonal),correoInstitucional:text(row.correoInstitucional||row.CorreoInstitucional),celular:text(row.celular||row.Celular||row.telefono),telegramUser:tg.telegramUser,telegramChatId:tg.telegramChatId,telegramUpdatedAt:tg.telegramUpdatedAt,telegramSource:tg.telegramSource,telegramCheckedAt:tg.telegramCheckedAt,telegramVerifiedAt:tg.telegramVerifiedAt,_telegramUser:tg.telegramUser,_telegramChatId:tg.telegramChatId,source:"v2_mirror",updatedAt:text(row.updatedAt)||now()});}
  function nota(row){var id=studentIdFrom(row);if(!id){return null;}return Object.assign({},row,{id:id,notaId:id,idEstudiantePeriodo:id,studentId:id,cedula:normalizeCedula(row.cedula),numeroIdentificacion:normalizeCedula(row.cedula),periodoId:period(row.periodoId),source:"v2_mirror",updatedAt:text(row.updatedAt)||now()});}
  function periodRows(row){var periodoId=text(row.id||row.periodoId),output=[];if(!periodoId){return output;}(row.carrerasDetectadas||[]).forEach(function(item){var label=text(item.nombre||item.label||item.carrera||item);if(label){output.push({type:"career",id:periodoId+"__"+key(label),periodoId:periodoId,carrera:label,updatedAt:now(),source:"v2_mirror"});}});(row.divisiones||[]).forEach(function(item){var label=text(item);if(label){output.push({type:"division",id:periodoId+"__"+key(label),periodoId:periodoId,division:label,updatedAt:now(),source:"v2_mirror"});}});return output;}

  function mirrorRows(storeName,rows,originalPut,originalBulkPut){var s=stores(),tasks=[];rows=Array.isArray(rows)?rows:[];if(!rows.length){return Promise.resolve({mirrored:0});}if(storeName===s.estudiantes){var people=rows.map(persona).filter(Boolean),enrollments=rows.map(matricula).filter(Boolean),contacts=rows.map(contacto).filter(Boolean),divisions=rows.map(division).filter(Boolean);if(people.length){tasks.push(mergedPut(s.personas,people,originalBulkPut));}if(enrollments.length){tasks.push(mergedPut(s.matriculas,enrollments,originalBulkPut));}if(contacts.length){tasks.push(mergedPut(s.contactosV2,contacts,originalBulkPut));}if(divisions.length){tasks.push(mergedPut(s.divisiones,divisions,originalBulkPut));}}if(storeName===s.requisitos){var requirements=rows.map(requisito).filter(Boolean);if(requirements.length){tasks.push(mergedPut(s.requisitosV2,requirements,originalBulkPut));}}if(storeName===s.contactos){var contactRows=rows.map(legacyContact).filter(Boolean);if(contactRows.length){tasks.push(mergedPut(s.contactosV2,contactRows,originalBulkPut));}}if(storeName===s.notas){var notes=rows.map(nota).filter(Boolean);if(notes.length){tasks.push(mergedPut(s.notasV2,notes,originalBulkPut));}}if(storeName===s.periodos){rows.forEach(function(item){periodRows(item).forEach(function(row){tasks.push(originalPut(row.type==="career"?s.periodosCarreras:s.periodosDivisiones,row));});});}return tasks.length?Promise.all(tasks).then(function(){return {mirrored:tasks.length};}):Promise.resolve({mirrored:0});}

  function exposeCoreTelegram(){var core=window.BL2Core,repo=window.BDLRepoContactos;if(!core||!repo||!repo.saveTelegramForCedula){return false;}core.updateTelegramByCedula=function(cedula,data,options){return repo.saveTelegramForCedula(cedula,data,Object.assign({source:"BL2Core.telegram_local"},options||{}));};core.actualizarTelegramPorCedula=core.updateTelegramByCedula;core.guardarTelegram=core.updateTelegramByCedula;core.__telegramLocalOnly=true;return true;}
  function install(){var current=window.BL2DB;if(!current||!current.put||!current.bulkPut){return false;}if(current.__v2MirrorInstalled){exposeCoreTelegram();return true;}var originalPut=current.put.bind(current),originalBulkPut=current.bulkPut.bind(current);current.put=function(storeName,value){return originalPut(storeName,value).then(function(saved){return mirrorRows(storeName,[saved||value],originalPut,originalBulkPut).catch(function(error){try{console.warn("[BDLV2Mirror]",error);}catch(inner){}}).then(function(){return saved;});});};current.bulkPut=function(storeName,rows){rows=Array.isArray(rows)?rows:[];return originalBulkPut(storeName,rows).then(function(saved){return mirrorRows(storeName,saved&&saved.length?saved:rows,originalPut,originalBulkPut).catch(function(error){try{console.warn("[BDLV2Mirror]",error);}catch(inner){}}).then(function(){return saved;});});};current.__v2MirrorInstalled=true;current.v2MirrorVersion=VERSION;exposeCoreTelegram();try{window.dispatchEvent(new CustomEvent("bdlocal:v2-mirror-ready",{detail:{version:VERSION,at:now(),telegramSafe:true,canonicalLocalId:"cedula__periodoId"}}));}catch(error){}return true;}

  window.BDLV2Mirror={version:VERSION,install:install,mirrorRows:mirrorRows,mergeNonEmpty:merge,personaFromStudent:persona,contactFromStudent:contacto,studentIdFrom:studentIdFrom,exposeCoreTelegram:exposeCoreTelegram};
  install();
})(window);
