/* =========================================================
Nombre completo: titulacion.app.js
Ruta o ubicación: /Requisitos/Titulacion/frontend/titulacion.app.js
Función o funciones:
- Orquestar la pantalla Infor.
- Manejar período, Excel, unión BaseLocal, cronogramas, anexos, Gemini y diagnóstico.
- Construir el motor del informe Regular/PVC.
- Integrar Gemini para análisis, conclusiones y recomendaciones.
- Exportar Word compatible y abrir vista PDF imprimible.
- Actualizar pasos visuales, revisión QA en vivo y validación previa a procesar.
Con qué se conecta:
- ../core/infor.periodo.js
- ../core/infor.excel.js
- ../core/infor.match.js
- ../core/infor.report.js
- ../core/infor.gemini.js
- ../core/infor.state.js
- ../core/infor.qa.js
- ../export/word/word.export.js
- ../export/pdf/pdf.from-word.js
- ../sections/cronograma/cronograma.parser.js
========================================================= */
(function(window, document){
  "use strict";

  var state = {periods:[], anexos:[], booted:false, periodSummary:null};
  function el(id){return document.getElementById(id);}
  function text(value){return String(value == null ? "" : value).trim();}
  function esc(value){return text(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
  function option(value,label,selected){return '<option value="' + esc(value) + '" ' + (selected ? 'selected' : '') + '>' + esc(label) + '</option>';}
  function status(message, cls){var box = el("infor-status");if(box){box.textContent = message;box.className = "infor-status " + (cls || "");}}
  function bind(id,eventName,handler){var node = el(id);if(node){node.addEventListener(eventName,handler);}}
  function periodo(){return window.InforPeriodo || null;}
  function periodIdOf(period){return periodo() ? periodo().periodIdOf(period) : text(period && (period.id || period.periodoId || period.value || period.key) || period);}
  function periodLabelOf(period){return periodo() ? periodo().periodLabelOf(period) : text(period && (period.label || period.periodoLabel || period.nombre || period.name || period.id || period.periodoId) || period);}
  function listPeriods(){return periodo() && typeof periodo().list === "function" ? periodo().list() : [];}

  function selectedPeriod(){var id = el("infor-periodo") ? el("infor-periodo").value : "";return state.periods.find(function(period){return periodIdOf(period) === id;}) || {id:id,label:id};}
  function fillPeriods(){var select = el("infor-periodo");if(!select){return;}var current = select.value;state.periods = listPeriods();select.innerHTML = option("", "Selecciona un período", !current) + state.periods.map(function(period){var id = periodIdOf(period);return option(id, periodLabelOf(period), current === id);}).join("");}
  function reportName(snapshot){snapshot = snapshot || window.InforState.getState();if(state.periodSummary && state.periodSummary.reportName){return state.periodSummary.reportName;}var label = text(snapshot.periodLabel || snapshot.periodId);return label ? "Informe de Titulación " + label : "—";}
  function setChip(id, label, cls){var node = el(id);if(!node){return;}node.textContent = label;node.className = "infor-chip " + (cls || "");}

  function updateFlow(snapshot){
    var steps = Array.prototype.slice.call(document.querySelectorAll(".infor-flow .infor-step"));
    if(!steps.length){return;}
    var hasPeriod = !!text(snapshot.periodId || snapshot.periodLabel);
    var excelRows = snapshot.excelData && Array.isArray(snapshot.excelData.rows) ? snapshot.excelData.rows.length : 0;
    var hasInsumos = excelRows > 0 || !!text(snapshot.cronogramas && (snapshot.cronogramas.complexivo || snapshot.cronogramas.trabajoTitulacion || snapshot.cronogramas.pvc)) || (Array.isArray(snapshot.anexos) && snapshot.anexos.length > 0);
    var reportReady = !!(snapshot.reportDraft && snapshot.reportDraft.ok);
    var stateMap = [{active:!hasPeriod, done:hasPeriod},{active:hasPeriod && !reportReady, done:hasInsumos && !!snapshot.matchResult},{active:reportReady, done:reportReady}];
    steps.forEach(function(step, index){var item = stateMap[index] || {active:false,done:false};step.classList.toggle("is-active", !!item.active && !item.done);step.classList.toggle("is-done", !!item.done);});
  }

  function readiness(snapshot){
    snapshot = snapshot || window.InforState.getState();
    var missing = [];
    var hasPeriod = !!text(snapshot.periodId || snapshot.periodLabel);
    var excelRows = snapshot.excelData && Array.isArray(snapshot.excelData.rows) ? snapshot.excelData.rows.length : 0;
    var hasGemini = !!(window.InforState && window.InforState.getGeminiKey && window.InforState.getGeminiKey());
    if(!hasPeriod){missing.push("seleccionar período");}
    if(!excelRows){missing.push("cargar Excel con estudiantes");}
    if(!hasGemini){missing.push("configurar Gemini");}
    return {ready:missing.length === 0, missing:missing, message:missing.length ? ("Falta: " + missing.join(", ") + ".") : "Listo para procesar el informe."};
  }

  function updateProcessReadiness(snapshot){
    var node = el("infor-process-readiness");
    var btn = el("infor-process");
    var info = readiness(snapshot);
    if(node){node.textContent = info.message;node.className = "infor-muted " + (info.ready ? "ok" : "warn");}
    if(btn){btn.title = info.message;}
    return info;
  }

  function updatePeriodSummary(snapshot){snapshot = snapshot || window.InforState.getState();if(periodo() && typeof periodo().summary === "function" && text(snapshot.periodId || snapshot.periodLabel)){state.periodSummary = periodo().summary({id:snapshot.periodId,label:snapshot.periodLabel});}else{state.periodSummary = null;}return state.periodSummary;}
  function renderModalidades(summary){var box = el("infor-modalidades");if(!box){return;}var list = summary && Array.isArray(summary.modalities) ? summary.modalities : [];if(!list.length){box.innerHTML = "<em>Selecciona un período.</em>";return;}box.innerHTML = list.map(function(item){var cls = item.locked ? " locked" : (item.default ? " default" : "");var tag = item.locked ? "fijo" : (item.default ? "por defecto" : "editable en Ficha");return '<span class="infor-mode-pill' + cls + '">' + esc(item.label) + ' · ' + esc(tag) + '</span>';}).join("");}
  function renderByPeriod(snapshot){snapshot = snapshot || window.InforState.getState();var summary = updatePeriodSummary(snapshot);var info = summary && summary.type ? summary.type : (snapshot.periodType || {id:"", label:"Sin período"});var isRegular = info.id === "REGULAR";setChip("infor-period-type", info.label || "Sin período", isRegular ? "ok" : (info.id === "PVC" ? "warn" : ""));setChip("infor-cronograma-mode", isRegular ? "Regular: Complexivo + Trabajo" : (info.id === "PVC" ? "PVC: Artículo Académico" : "Automático"), isRegular ? "ok" : (info.id === "PVC" ? "warn" : ""));if(el("infor-type-label")){el("infor-type-label").textContent = info.label || "—";}if(el("infor-source-label")){el("infor-source-label").textContent = summary && summary.students ? summary.students.source : "—";}if(el("infor-students-count")){el("infor-students-count").textContent = summary && summary.students ? String(summary.students.total || 0) : "0";}if(el("infor-report-name")){el("infor-report-name").textContent = reportName(snapshot);}renderModalidades(summary);if(el("infor-cronogramas-regular")){el("infor-cronogramas-regular").classList.toggle("is-hidden", !isRegular);}if(el("infor-cronogramas-pvc")){el("infor-cronogramas-pvc").classList.toggle("is-hidden", isRegular || !info.id);}}
  function renderGemini(){var hasKey = window.InforState.refreshGeminiFlag();setChip("infor-gemini-state", hasKey ? "Gemini configurado" : "Gemini sin clave", hasKey ? "ok" : "warn");}
  function renderExcel(snapshot){snapshot = snapshot || window.InforState.getState();var excel = snapshot.excel || {};setChip("infor-excel-state", excel.loaded ? "Excel leído" : "Sin Excel", excel.loaded ? "ok" : "warn");if(el("infor-excel-name")){el("infor-excel-name").textContent = excel.fileName || "—";}if(el("infor-excel-sheets")){el("infor-excel-sheets").textContent = String(excel.usefulSheets || 0);}if(el("infor-excel-ignored")){el("infor-excel-ignored").textContent = String(excel.ignoredSheets || 0);}if(el("infor-excel-rows")){el("infor-excel-rows").textContent = String(excel.totalRows || 0);}renderExcelPreview(snapshot);}
  function smallTable(headers, rows){if(!rows || !rows.length){return '<div class="infor-empty">Sin datos.</div>';}var html = '<div class="infor-table-wrap"><table class="infor-small-table"><thead><tr>' + headers.map(function(h){return '<th>' + esc(h.label) + '</th>';}).join("") + '</tr></thead><tbody>';html += rows.map(function(row){return '<tr>' + headers.map(function(h){var value = typeof h.value === "function" ? h.value(row) : row[h.key];return '<td>' + value + '</td>';}).join("") + '</tr>';}).join("");return html + '</tbody></table></div>';}
  function renderExcelPreview(snapshot){var box = el("infor-excel-preview");if(!box){return;}var data = snapshot.excelData || {};var sheets = Array.isArray(data.sheets) ? data.sheets : [];if(!sheets.length){box.innerHTML = '<div class="infor-empty">Sin Excel leído.</div>';return;}box.innerHTML = smallTable([{label:"Hoja", value:function(r){return esc(r.name);}},{label:"Filas", value:function(r){return esc(r.totalRows || 0);}},{label:"Estudiantes", value:function(r){return '<span class="infor-pill-mini ' + (r.detectedStudents ? 'ok' : 'warn') + '">' + esc(r.detectedStudents || 0) + '</span>'; }},{label:"Estado", value:function(r){return r.ignored ? '<span class="infor-pill-mini warn">Ignorada</span>' : '<span class="infor-pill-mini ok">Útil</span>'; }},{label:"Detalle", value:function(r){return esc(r.reason || 'Procesada');}}], sheets);}
  function runMatch(){var snapshot = window.InforState.getState();if(!(window.InforMatch && typeof window.InforMatch.match === "function")){return null;}if(!(snapshot.excelData && Array.isArray(snapshot.excelData.rows) && snapshot.excelData.rows.length)){return null;}var result = window.InforMatch.match(snapshot);window.InforState.setMatchResult(result);return result;}
  function renderMatch(snapshot){snapshot = snapshot || window.InforState.getState();var result = snapshot.matchResult || null;var summary = result && result.summary ? result.summary : {unidos:0,pendientes:0,porCedula:0,porNombre:0,total:0};setChip("infor-match-state", result && result.ok ? "Unión lista" : "Sin unión", result && result.ok ? (summary.pendientes ? "warn" : "ok") : "warn");if(el("infor-match-unidos")){el("infor-match-unidos").textContent = String(summary.unidos || 0);}if(el("infor-match-pendientes")){el("infor-match-pendientes").textContent = String(summary.pendientes || 0);}if(el("infor-match-cedula")){el("infor-match-cedula").textContent = String(summary.porCedula || 0);}if(el("infor-match-nombre")){el("infor-match-nombre").textContent = String(summary.porNombre || 0);}var box = el("infor-match-preview");if(!box){return;}if(!(result && Array.isArray(result.matches) && result.matches.length)){box.innerHTML = '<div class="infor-empty">Carga un Excel para unir con BaseLocal.</div>';return;}box.innerHTML = smallTable([{label:"Estado", value:function(r){return r.status === "unido" ? '<span class="infor-pill-mini ok">Unido</span>' : '<span class="infor-pill-mini warn">Pendiente</span>'; }},{label:"Método", value:function(r){return esc(r.method === "cedula" ? "Cédula" : r.method === "nombre" ? "Nombre" : "Sin match");}},{label:"Cédula", value:function(r){return esc(r.cedula || '—');}},{label:"Estudiante", value:function(r){return esc(r.nombres || '—');}},{label:"Carrera", value:function(r){return esc(r.carrera || '—');}},{label:"Modalidad", value:function(r){return esc(r.modalidadLabel || '—');}}], result.matches.slice(0, 20));}
  function setExportButtons(ready){var w = el("infor-export-word"), p = el("infor-export-pdf");if(w){w.disabled = !ready;}if(p){p.disabled = !ready;}}
  function renderReport(snapshot){snapshot = snapshot || window.InforState.getState();var report = snapshot.reportDraft || null;var statusInfo = snapshot.reportStatus || {};var ready = !!(report && report.ok);setExportButtons(ready);setChip("infor-report-state", ready ? "Motor listo" : "Sin motor", ready ? "ok" : "warn");if(el("infor-report-kind")){el("infor-report-kind").textContent = report ? report.kind : "—";}if(el("infor-report-total")){el("infor-report-total").textContent = report && report.resumen ? String(report.resumen.total || 0) : "0";}if(el("infor-report-approved")){el("infor-report-approved").textContent = report && report.resumen ? String(report.resumen.aprobados || 0) : "0";}if(el("infor-report-sections")){el("infor-report-sections").textContent = report && report.sections ? String(report.sections.length) : "0";}var box = el("infor-report-preview");if(!box){return;}if(!ready){box.innerHTML = '<div class="infor-empty">' + esc(statusInfo.message || 'Presiona Procesar para construir el motor del informe.') + '</div>';return;}box.innerHTML = smallTable([{label:"Sección", value:function(r){return esc(r.title || r.id);}},{label:"Tipo", value:function(r){return esc(r.type || '—');}},{label:"Registros", value:function(r){return esc(r.rows ? r.rows.length : (r.carreras ? r.carreras.length : '—'));}},{label:"Estado", value:function(){return '<span class="infor-pill-mini ok">Lista</span>';}}], report.sections || []);}
  function renderCronogramas(snapshot){snapshot = snapshot || window.InforState.getState();var c = snapshot.cronogramas || {};if(el("infor-cronograma-complexivo") && el("infor-cronograma-complexivo").value !== text(c.complexivo)){el("infor-cronograma-complexivo").value = text(c.complexivo);}if(el("infor-cronograma-trabajo") && el("infor-cronograma-trabajo").value !== text(c.trabajoTitulacion)){el("infor-cronograma-trabajo").value = text(c.trabajoTitulacion);}if(el("infor-cronograma-pvc") && el("infor-cronograma-pvc").value !== text(c.pvc)){el("infor-cronograma-pvc").value = text(c.pvc);}renderCronogramaPreview(snapshot);}
  function cronogramaTitle(kind){if(kind === "complexivo"){return "Examen Complexivo";}if(kind === "trabajoTitulacion"){return "Trabajo de Titulación";}if(kind === "pvc"){return "Artículo Académico PVC";}return kind;}
  function renderCronogramaPreview(snapshot){var box = el("infor-cronograma-preview");if(!box){return;}var parsed = snapshot.cronogramasParsed || {};var type = snapshot.periodType || {};var kinds = type.id === "REGULAR" ? ["complexivo","trabajoTitulacion"] : (type.id === "PVC" ? ["pvc"] : []);var cards = [];kinds.forEach(function(kind){var info = parsed[kind];if(info && info.ok){cards.push('<article class="infor-preview-card"><h3>' + esc(cronogramaTitle(kind)) + '</h3><p>' + esc((info.rows || []).length) + ' actividades interpretadas.</p>' + smallTable([{label:"Fecha", value:function(r){return esc(r.fecha || '—');}},{label:"Actividad", value:function(r){return esc(r.actividad || '—');}},{label:"Responsable", value:function(r){return esc(r.responsable || '—');}},{label:"Observación", value:function(r){return esc(r.observacion || '—');}}], (info.rows || []).slice(0, 8)) + '</article>');}});box.innerHTML = cards.length ? cards.join("") : '<div class="infor-empty">Pega un cronograma para ver la tabla interpretada.</div>';}
  function renderAnexos(){var box = el("infor-anexos-list");if(el("infor-anexos-count")){el("infor-anexos-count").textContent = state.anexos.length + " anexos";}if(!box){return;}if(!state.anexos.length){box.innerHTML = '<div class="infor-empty">Sin anexos cargados.</div>';return;}box.innerHTML = state.anexos.map(function(item, index){return '<article class="infor-anexo" data-index="' + index + '">' + (item.preview ? '<img src="' + esc(item.preview) + '" alt="' + esc(item.title || item.name) + '">' : '') + '<input class="infor-anexo-title" type="text" data-title-index="' + index + '" value="' + esc(item.title || '') + '" placeholder="Título del anexo" />' + '<div class="infor-anexo-meta"><span>' + esc(item.name || 'imagen') + '</span><span>' + Math.round((item.size || 0)/1024) + ' KB</span></div>' + '</article>';}).join("");}
  function saveAnexosToState(){window.InforState.setAnexos(state.anexos.map(function(item){return {name:item.name,size:item.size,type:item.type,title:item.title || item.name,createdAt:item.createdAt};}));renderDiagnostics();}
  function renderDiagnostics(){var node = el("infor-diagnostics");if(!node){return;}var snapshot = window.InforState.getState();node.textContent = JSON.stringify({bloque:"Bloque validación - Requisitos antes de procesar",generatedAt:new Date().toISOString(),periodId:snapshot.periodId,periodLabel:snapshot.periodLabel,periodType:snapshot.periodType,periodSummary:state.periodSummary,excel:snapshot.excel,excelRows:snapshot.excelData && snapshot.excelData.rows ? snapshot.excelData.rows.length : 0,matchSummary:snapshot.matchResult && snapshot.matchResult.summary,reportStatus:snapshot.reportStatus,reportResumen:snapshot.reportDraft && snapshot.reportDraft.resumen,reportKind:snapshot.reportDraft && snapshot.reportDraft.kind,reportSections:snapshot.reportDraft && snapshot.reportDraft.sections ? snapshot.reportDraft.sections.length : 0,geminiAnalysis:!!snapshot.geminiAnalysis,cronogramasParsed:snapshot.cronogramasParsed,anexos:state.anexos.map(function(x){return {name:x.name,title:x.title,size:x.size,type:x.type};}),gemini:snapshot.gemini,lastProcess:snapshot.lastProcess,diagnostics:snapshot.diagnostics}, null, 2);}
  function renderQA(){try{if(window.InforQA && typeof window.InforQA.run === "function" && typeof window.InforQA.render === "function"){window.InforQA.render(window.InforQA.run());}}catch(error){console.warn("[Infor QA render]", error);}}
  function renderAll(message, cls){var snapshot = window.InforState.getState();updateFlow(snapshot);renderByPeriod(snapshot);renderGemini();renderExcel(snapshot);renderMatch(snapshot);renderReport(snapshot);renderCronogramas(snapshot);renderAnexos();updateProcessReadiness(snapshot);renderDiagnostics();renderQA();if(message){status(message, cls || "ok");}}
  function onPeriodChange(){var period = selectedPeriod();var id = periodIdOf(period);var label = periodLabelOf(period);if(!id){window.InforState.loadPeriod("", "");renderAll("Selecciona un período para iniciar.", "warn");return;}window.InforState.loadPeriod(id, label);if((window.InforState.getState().excelData.rows || []).length){runMatch();}renderAll("Período cargado: " + label + ".", "ok");}
  async function onExcelChange(event){var file = event.target.files && event.target.files[0];if(!file){return;}try{status("Leyendo Excel desde Infor...", "warn");if(!(window.InforExcel && typeof window.InforExcel.readFile === "function")){throw new Error("InforExcel no está disponible.");}var analysis = await window.InforExcel.readFile(file);window.InforState.setExcelAnalysis(analysis);runMatch();renderAll("Excel leído y unido: " + (analysis.usefulSheets || 0) + " hojas útiles, " + (analysis.totalRows || 0) + " filas detectadas.", "ok");}catch(error){console.error("[Infor Excel]", error);window.InforState.setExcelInfo({fileName:file.name,size:file.size,type:file.type || "",loaded:false,sheetCount:0,ignoredSheets:0,usefulSheets:0,totalRows:0,error:error.message || String(error)});renderAll("No se pudo leer el Excel: " + (error.message || String(error)), "bad");}}
  function parseCronograma(kind, value){window.InforState.setCronograma(kind, value);if(window.InforCronogramaParser && typeof window.InforCronogramaParser.parse === "function"){window.InforState.setCronogramaParsed(kind, window.InforCronogramaParser.parse(value));}}
  function onCronogramaInput(kind, value){parseCronograma(kind, value);renderCronogramas(window.InforState.getState());updateProcessReadiness(window.InforState.getState());renderDiagnostics();renderQA();}
  function reparseAllCronogramas(){var snapshot = window.InforState.getState();var c = snapshot.cronogramas || {};if(window.InforCronogramaParser && typeof window.InforCronogramaParser.parseMany === "function"){window.InforState.setCronogramasParsed(window.InforCronogramaParser.parseMany(c));}}
  function onAnexosChange(event){var files = Array.prototype.slice.call(event.target.files || []);var mapped = files.filter(function(file){return /^image\//.test(file.type || "");}).map(function(file){return {name:file.name,size:file.size,type:file.type,title:file.name,createdAt:new Date().toISOString(),preview:URL.createObjectURL(file)};});state.anexos = state.anexos.concat(mapped);saveAnexosToState();renderAnexos();updateProcessReadiness(window.InforState.getState());renderDiagnostics();renderQA();status(mapped.length ? "Anexos cargados: " + mapped.length + "." : "No se detectaron imágenes válidas.", mapped.length ? "ok" : "warn");}
  function openGemini(){var modal = el("infor-gemini-modal");if(modal){modal.classList.remove("is-hidden");}if(el("infor-gemini-key")){el("infor-gemini-key").value = window.InforState.getGeminiKey();el("infor-gemini-key").focus();}}
  function closeGemini(){var modal = el("infor-gemini-modal");if(modal){modal.classList.add("is-hidden");}}
  function saveGemini(){window.InforState.setGeminiKey(el("infor-gemini-key") ? el("infor-gemini-key").value : "");closeGemini();renderAll("Clave Gemini guardada localmente.", "ok");}
  function clearGemini(){window.InforState.setGeminiKey("");if(el("infor-gemini-key")){el("infor-gemini-key").value = "";}renderAll("Clave Gemini eliminada.", "warn");}
  async function process(){var snapshot = window.InforState.getState();var gate = readiness(snapshot);if(!gate.ready){renderAll(gate.message, "warn");return;}try{status("Construyendo motor del informe...", "warn");reparseAllCronogramas();snapshot = window.InforState.getState();if((snapshot.excelData && snapshot.excelData.rows || []).length){runMatch();}snapshot = window.InforState.getState();if(!(window.InforReport && typeof window.InforReport.build === "function")){throw new Error("InforReport no está disponible.");}var baseReport = window.InforReport.build(snapshot, null);if(!baseReport.ok){throw new Error("No hay estudiantes unidos o detectados para construir el informe.");}var key = window.InforState.getGeminiKey();if(!key){throw new Error("Proceso detenido: falta configurar la clave de Gemini.");}if(!(window.InforGemini && typeof window.InforGemini.generate === "function")){throw new Error("InforGemini no está disponible.");}status("Enviando resumen a Gemini...", "warn");var analysis = await window.InforGemini.generate(baseReport, key);var finalReport = window.InforReport.build(snapshot, analysis);window.InforState.setReportDraft(finalReport, analysis);window.InforState.processDraft();renderAll("Informe listo para exportar en Word o PDF.", "ok");}catch(error){console.error("[Infor process]", error);window.InforState.setReportError(error.message || String(error));renderAll(error.message || String(error), "bad");}}
  function currentReport(){var snapshot = window.InforState.getState();var report = snapshot.reportDraft || null;if(!(report && report.ok)){throw new Error("Primero procesa el informe correctamente.");}return report;}
  function exportWord(){try{if(!(window.InforWordExport && typeof window.InforWordExport.download === "function")){throw new Error("InforWordExport no está disponible.");}var result = window.InforWordExport.download(currentReport(), state.anexos);status("Word generado: " + result.filename + ".", "ok");}catch(error){console.error("[Infor Word]", error);status(error.message || String(error), "bad");}}
  function exportPdf(){try{if(!(window.InforPdfExport && typeof window.InforPdfExport.print === "function")){throw new Error("InforPdfExport no está disponible.");}window.InforPdfExport.print(currentReport(), state.anexos);status("Vista PDF abierta. Guarda como PDF desde la ventana de impresión.", "ok");}catch(error){console.error("[Infor PDF]", error);status(error.message || String(error), "bad");}}
  function bindEvents(){bind("infor-periodo", "change", onPeriodChange);bind("infor-excel-file", "change", onExcelChange);bind("infor-cronograma-complexivo", "input", function(e){onCronogramaInput("complexivo", e.target.value);});bind("infor-cronograma-trabajo", "input", function(e){onCronogramaInput("trabajoTitulacion", e.target.value);});bind("infor-cronograma-pvc", "input", function(e){onCronogramaInput("pvc", e.target.value);});bind("infor-anexos-input", "change", onAnexosChange);bind("infor-anexos-list", "input", function(e){var index = e.target && e.target.getAttribute ? Number(e.target.getAttribute("data-title-index")) : -1;if(index >= 0 && state.anexos[index]){state.anexos[index].title = e.target.value;saveAnexosToState();renderDiagnostics();renderQA();}});bind("infor-gemini-open", "click", openGemini);bind("infor-gemini-close", "click", closeGemini);bind("infor-gemini-save", "click", saveGemini);bind("infor-gemini-clear", "click", clearGemini);bind("infor-process", "click", process);bind("infor-export-word", "click", exportWord);bind("infor-export-pdf", "click", exportPdf);bind("infor-gemini-modal", "click", function(e){if(e.target && e.target.id === "infor-gemini-modal"){closeGemini();}});}
  function boot(){try{fillPeriods();bindEvents();window.InforState.loadPeriod("", "");renderAll(state.periods.length ? "Infor listo. Selecciona un período y carga los insumos." : "Infor listo, pero no encontré períodos cargados todavía.", state.periods.length ? "ok" : "warn");state.booted = true;}catch(error){console.error("[Infor boot]", error);status(error.message || String(error), "bad");}}
  if(document.readyState === "loading"){document.addEventListener("DOMContentLoaded", boot);}else{boot();}
  window.InforApp = {render:renderAll,getState:function(){return Object.assign({}, state);},runMatch:runMatch,process:process,exportWord:exportWord,exportPdf:exportPdf};
})(window, document);
