/* =========================================================
Nombre completo: baselocal.core.js
Ruta o ubicación: /Requisitos/BaseLocal/baselocal.core.js
Función o funciones:
- Entregar API liviana para la pantalla Base Local.
- Usar BL2EstudiantesRepo/BL2PeriodosRepo como camino principal.
- Evitar BL2DataEngine y snapshot completo durante la vista normal.
- Mantener operaciones de divisiones y diagnóstico bajo demanda.
========================================================= */
(function(window){
  "use strict";

  var VERSION = "2.0.0-screen-safe-core";
  var snapshotCache = {snapshot:null, cachedAt:0};
  var CACHE_MS = 1200;

  function text(value){return String(value == null ? "" : value).trim();}
  function norm(value){return text(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, " ").trim().toLowerCase();}
  function clone(value){try{return JSON.parse(JSON.stringify(value == null ? null : value));}catch(error){return value;}}
  function now(){return new Date().toISOString();}
  function repo(){return window.ExcelLocalRepo || null;}
  function storage(){return window.ExcelLocalStorage || null;}
  function filtros(){return window.BLFiltros || null;}
  function divisiones(){return window.BLDivisionesService || null;}
  function periodsRepo(){return window.BL2PeriodosRepo || null;}
  function studentsRepo(){return window.BL2EstudiantesRepo || null;}
  function periodosService(){return window.BLPeriodosService || null;}
  function parentSession(){try{if(window.parent && window.parent !== window && window.parent.MAQ_BASELOCAL_SESSION){return window.parent.MAQ_BASELOCAL_SESSION;}}catch(error){}try{if(window.top && window.top !== window && window.top.MAQ_BASELOCAL_SESSION){return window.top.MAQ_BASELOCAL_SESSION;}}catch(error){}try{if(window.MAQ_BASELOCAL_SESSION){return window.MAQ_BASELOCAL_SESSION;}}catch(error){}return null;}
  function normalizeSnapshotShape(snapshot){var snap = snapshot && typeof snapshot === "object" ? snapshot : {meta:{},periods:[],students:[],history:[],diagnostics:[]};snap.meta = snap.meta && typeof snap.meta === "object" ? snap.meta : {};snap.periods = Array.isArray(snap.periods) ? snap.periods : [];snap.students = Array.isArray(snap.students) ? snap.students : [];snap.history = Array.isArray(snap.history) ? snap.history : [];snap.diagnostics = Array.isArray(snap.diagnostics) ? snap.diagnostics : [];if(!snap.periods.length && snap.students.length && periodosService() && typeof periodosService().inferFromStudents === "function"){snap.periods = periodosService().inferFromStudents(snap.students);}return snap;}
  function getSnapshot(options){options = options || {};if(options.force !== true && snapshotCache.snapshot && Date.now() - snapshotCache.cachedAt < CACHE_MS){return snapshotCache.snapshot;}var snap = null;var session = parentSession();try{if(session && typeof session.getSnapshot === "function"){snap = session.getSnapshot({clone:false, force:options.force === true});}}catch(error){snap = null;}try{if(!snap && storage() && typeof storage().readSnapshot === "function"){snap = storage().readSnapshot({session:false, clone:false});}}catch(error){snap = null;}try{if(!snap && repo() && typeof repo().getSnapshot === "function"){snap = repo().getSnapshot();}}catch(error){snap = null;}snap = normalizeSnapshotShape(snap);snapshotCache = {snapshot:snap, cachedAt:Date.now()};return snap;}
  function clearSnapshotCache(){snapshotCache = {snapshot:null, cachedAt:0};try{if(filtros() && filtros().clearCache){filtros().clearCache();}}catch(error){}try{if(studentsRepo() && studentsRepo().invalidate){studentsRepo().invalidate();}}catch(error){}try{if(periodsRepo() && periodsRepo().invalidate){periodsRepo().invalidate();}}catch(error){}}
  function samePeriod(a,b){if(!text(b)){return true;}try{if(window.BLPeriodosCanon && typeof window.BLPeriodosCanon.samePeriod === "function"){return window.BLPeriodosCanon.samePeriod(a,b);}}catch(error){}return norm(a) === norm(b);}
  function rowPeriod(row){row = row || {};return text(row.periodoId || row.ultimoPeriodoId || row.periodoLabel || row.periodo || row._bl2PeriodoId || row._bl2Periodo);}
  function carreraOf(row){row = row || {};return text(row.nombreCarrera || row.nombrecarrera || row.NombreCarrera || row.carrera || row.Carrera || row._bl2Carrera) || "SIN CARRERA";}
  function divisionOf(row){try{if(divisiones() && typeof divisiones().studentDivision === "function"){return divisiones().studentDivision(row || {});}}catch(error){}var list = Array.isArray(row && row.divisiones) ? row.divisiones : [];return list[0] || (row && (row.division || row._bl2Division)) || "Sin división";}
  function estadoOf(row){row = row || {};var raw = text(row.estadoMatricula || row._bl2EstadoMatricula || "ACTIVO").toUpperCase();return raw === "RETIRADO" ? "RETIRADO" : "ACTIVO";}

  function getPeriods(snapshot){try{if(periodsRepo() && typeof periodsRepo().listar === "function"){var rows = periodsRepo().listar();if(Array.isArray(rows) && rows.length){return rows;}}}catch(error){}snapshot = snapshot || getSnapshot();if(Array.isArray(snapshot.periods) && snapshot.periods.length){return snapshot.periods.slice();}if(periodosService() && typeof periodosService().inferFromStudents === "function"){return periodosService().inferFromStudents(snapshot.students || []);}return [];}
  function repoStudentsPage(periodId, search, estadoMatricula, options){options = options || {};var payload = {periodId:periodId || "", periodoId:periodId || "", search:search || "", q:search || "", estadoMatricula:estadoMatricula == null ? "ACTIVO" : estadoMatricula, matricula:estadoMatricula == null ? "ACTIVO" : estadoMatricula, division:options.division || "", offset:options.offset || 0, limit:options.limit || 100, countTotal:options.countTotal !== false};try{if(studentsRepo() && typeof studentsRepo().listarPagina === "function"){var result = studentsRepo().listarPagina(payload);if(result && Array.isArray(result.rows)){return {rows:result.rows,total:Number(result.total == null ? result.rows.length : result.total) || 0,offset:payload.offset,limit:payload.limit,source:result.source || "BL2EstudiantesRepo"};}}}catch(error){console.warn("[BaseLocalAPI BL2EstudiantesRepo]", error);}try{if(window.BL2 && window.BL2.estudiantes && typeof window.BL2.estudiantes.listarPagina === "function"){var bl2 = window.BL2.estudiantes.listarPagina(payload);if(bl2 && Array.isArray(bl2.rows)){return {rows:bl2.rows,total:Number(bl2.total == null ? bl2.rows.length : bl2.total) || 0,offset:payload.offset,limit:payload.limit,source:bl2.source || "BL2"};}}}catch(error2){console.warn("[BaseLocalAPI BL2]", error2);}return null;}
  function getStudentsPage(periodId, search, estadoMatricula, options, snapshot){options = options || {};var repoResult = repoStudentsPage(periodId, search, estadoMatricula, options);if(repoResult){return repoResult;}snapshot = snapshot || getSnapshot();if(filtros() && typeof filtros().filterStudentsPage === "function"){return filtros().filterStudentsPage(snapshot.students || [], {periodoId:periodId || "", search:search || "", estadoMatricula:estadoMatricula == null ? "ACTIVO" : estadoMatricula, division:options.division || "", offset:options.offset || 0, limit:options.limit || 100, countTotal:options.countTotal !== false});}var rows = (snapshot.students || []).slice(options.offset || 0, (options.offset || 0) + (options.limit || 100));return {rows:rows,total:(snapshot.students || []).length,offset:options.offset || 0,limit:options.limit || 100,source:"snapshot_fallback"};}
  function getStudents(periodId, search, estadoMatricula, snapshot){var page = getStudentsPage(periodId, search, estadoMatricula, {offset:0, limit:500, countTotal:false}, snapshot);return page.rows || [];}
  function getHistory(snapshot){snapshot = snapshot || getSnapshot();return (snapshot.history || []).slice().reverse();}
  function getDivisions(periodId, snapshot){try{if(studentsRepo() && typeof studentsRepo().listDivisions === "function"){return studentsRepo().listDivisions({periodoId:periodId || "", limit:5000, allowLarge:true});}}catch(error){}snapshot = snapshot || getSnapshot();if(divisiones() && typeof divisiones().listDivisions === "function"){return divisiones().listDivisions(snapshot.students || [], periodId || "");}var map = {}; (snapshot.students || []).forEach(function(row){if(periodId && !samePeriod(rowPeriod(row), periodId)){return;}map[divisionOf(row)] = true;});return Object.keys(map).sort(function(a,b){return a.localeCompare(b,"es");});}
  function getDivisionsWithEmpty(periodId, snapshot){var rows = getDivisions(periodId, snapshot);return rows.indexOf("Sin división") >= 0 ? rows : ["Sin división"].concat(rows);}
  function getAvailableDivisionCareers(periodId, snapshot){snapshot = snapshot || getSnapshot();if(divisiones() && typeof divisiones().availableCareers === "function"){return divisiones().availableCareers(snapshot.students || [], periodId || "");}var map = {}; (snapshot.students || []).forEach(function(row){if(periodId && !samePeriod(rowPeriod(row), periodId)){return;}map[carreraOf(row)] = true;});return Object.keys(map).sort(function(a,b){return a.localeCompare(b,"es");});}
  function getDivisionsSummary(periodId, snapshot){snapshot = snapshot || getSnapshot();if(divisiones() && typeof divisiones().divisionsSummary === "function"){return divisiones().divisionsSummary(snapshot.students || [], periodId || "");}var map = {}; (snapshot.students || []).forEach(function(row){if(periodId && !samePeriod(rowPeriod(row), periodId)){return;}var d = divisionOf(row);map[d] = (map[d] || 0) + 1;});return map;}
  function getDivisionDetail(periodId, divisionName, snapshot){snapshot = snapshot || getSnapshot();var wanted = norm(divisionName);var carreras = {}, total = 0;(snapshot.students || []).forEach(function(row){if(periodId && !samePeriod(rowPeriod(row), periodId)){return;}if(norm(divisionOf(row)) !== wanted){return;}carreras[carreraOf(row)] = true;total += 1;});return {periodId:periodId || "", division:divisionName || "", carreras:Object.keys(carreras).sort(function(a,b){return a.localeCompare(b,"es");}), total:total};}
  function countByStatus(rows){var out = {ACTIVO:0, RETIRADO:0, TOTAL:0};(rows || []).forEach(function(row){var e = estadoOf(row);out[e] = (out[e] || 0) + 1;out.TOTAL += 1;});return out;}
  function getDiagnostics(snapshot){snapshot = snapshot || getSnapshot({force:true});var careers = {}; (snapshot.students || []).forEach(function(row){careers[carreraOf(row)] = (careers[carreraOf(row)] || 0) + 1;});return {ok:true,mode:"diagnostico_bajo_demanda",version:VERSION,updatedAt:snapshot.meta && snapshot.meta.updatedAt,totalPeriods:(snapshot.periods || []).length,totalStudents:(snapshot.students || []).length,totalHistory:(snapshot.history || []).length,careers:careers,meta:snapshot.meta || {},statusCounts:countByStatus(snapshot.students || []),divisiones:getDivisionsSummary("", snapshot),baseLocalServices:{bl2Estudiantes:!!studentsRepo(),bl2Periodos:!!periodsRepo(),bl2Storage:!!window.BL2Storage,blFiltros:!!filtros()},health:window.BLHealthCheck && typeof window.BLHealthCheck.run === "function" ? window.BLHealthCheck.run(snapshot) : {ok:true, mode:"sin_healthcheck"}};}
  function writeSnapshot(snapshot, options){options = options || {};var clean = normalizeSnapshotShape(snapshot);clean.meta = Object.assign({}, clean.meta || {}, {updatedAt:now(), totalStudents:clean.students.length, totalPeriods:clean.periods.length});if(window.RequisitosBL && typeof window.RequisitosBL.writeSnapshot === "function"){window.RequisitosBL.writeSnapshot(clean);}else if(storage() && typeof storage().writeSnapshot === "function"){storage().writeSnapshot(clean);}else{throw new Error("No hay escritura disponible para Base Local.");}clearSnapshotCache();try{window.dispatchEvent(new CustomEvent("requisitos:bl:snapshot-changed", {detail:{source:options.source || "BaseLocalAPI", updatedAt:now()}}));}catch(error){}return clean;}
  function periodLabelForHistory(snapshot, periodId){return (getPeriods(snapshot).find(function(p){return samePeriod(p.id, periodId);}) || {}).label || periodId;}
  function createDivision(periodId, divisionName){periodId = text(periodId);divisionName = text(divisionName);if(!periodId){throw new Error("Selecciona un período antes de crear la división.");}if(!divisionName){throw new Error("Escribe el nombre de la división.");}var snapshot = clone(getSnapshot({force:true}));snapshot.history = snapshot.history || [];snapshot.history.unshift({id:"division_create_" + Date.now(), action:"crearDivision", periodoId:periodId, periodoLabel:periodLabelForHistory(snapshot, periodId), fileName:"Base Local", division:divisionName, totalRows:0, createdAt:now()});var saved = writeSnapshot(snapshot, {source:"division-create"});return {ok:true, action:"crearDivision", periodId:periodId, division:divisionName, updated:0, snapshot:saved, message:"División creada: " + divisionName};}
  function applyDivisionToCareers(periodId, divisionName, careers){periodId = text(periodId);divisionName = text(divisionName);if(!periodId){throw new Error("Selecciona un período antes de guardar la división.");}if(!divisionName){throw new Error("Escribe el nombre de la división.");}var snapshot = clone(getSnapshot({force:true}));var applied = divisiones() && typeof divisiones().applyDivision === "function" ? divisiones().applyDivision(snapshot.students || [], periodId, divisionName, careers || []) : {students:snapshot.students || [], updated:0};snapshot.students = applied.students;snapshot.history = snapshot.history || [];snapshot.history.unshift({id:"division_apply_" + Date.now(), action:"aplicarDivision", periodoId:periodId, periodoLabel:periodLabelForHistory(snapshot, periodId), fileName:"Base Local", division:divisionName, carreras:(careers || []).slice(), totalRows:applied.updated || 0, createdAt:now()});var saved = writeSnapshot(snapshot, {source:"division-apply"});return {ok:true, action:"aplicarDivision", periodId:periodId, division:divisionName, careers:(careers || []).slice(), updated:applied.updated || 0, snapshot:saved, message:"División guardada: " + divisionName};}
  function replaceDivisionToCareers(periodId, oldDivisionName, divisionName, careers){var snapshot = clone(getSnapshot({force:true}));if(divisiones() && oldDivisionName && typeof divisiones().clearDivision === "function"){snapshot.students = divisiones().clearDivision(snapshot.students || [], periodId, oldDivisionName).students;}return applyDivisionToCareers(periodId, divisionName, careers || []);}
  function deleteDivision(periodId, divisionName){periodId = text(periodId);divisionName = text(divisionName);if(!periodId){throw new Error("Selecciona un período antes de borrar la división.");}if(!divisionName){throw new Error("Selecciona la división que deseas borrar.");}var snapshot = clone(getSnapshot({force:true}));var cleared = divisiones() && typeof divisiones().clearDivision === "function" ? divisiones().clearDivision(snapshot.students || [], periodId, divisionName) : {students:snapshot.students || [], updated:0};snapshot.students = cleared.students;snapshot.history = snapshot.history || [];snapshot.history.unshift({id:"division_delete_" + Date.now(), action:"borrarDivision", periodoId:periodId, periodoLabel:periodLabelForHistory(snapshot, periodId), fileName:"Base Local", division:divisionName, totalRows:cleared.updated || 0, createdAt:now()});var saved = writeSnapshot(snapshot, {source:"division-delete"});return {ok:true, action:"borrarDivision", periodId:periodId, division:divisionName, updated:cleared.updated || 0, snapshot:saved};}
  function buildView(periodId, search, estadoMatricula, options){options = options || {};var snapshot = options.skipSnapshot === true ? {meta:{},periods:[],students:[],history:[],diagnostics:[]} : getSnapshot({force:options.force === true});var studentsResult = options.skipStudents === true ? {rows:[],total:0,offset:options.offset || 0,limit:options.limit || 100,source:"skip"} : getStudentsPage(periodId, search, estadoMatricula, options, snapshot);return {periods:getPeriods(snapshot),students:studentsResult.rows || [],renderStudents:studentsResult.rows || [],studentsPage:studentsResult,totalStudentsVisible:studentsResult.total || 0,statusCounts:{ACTIVO:0,RETIRADO:0,TOTAL:studentsResult.total || 0},totalStudentsPeriod:studentsResult.total || 0,history:options.includeHistory === true ? getHistory(snapshot) : [],historyCount:(snapshot.history || []).length,diagnostics:options.includeDiagnostics === true ? getDiagnostics(snapshot) : {ok:true,lazy:true},careersCount:0,divisions:options.includeDivisions === true ? getDivisionsWithEmpty(periodId || "", snapshot) : [],divisionsSummary:options.includeDivisionsSummary === true ? getDivisionsSummary(periodId || "", snapshot) : {},snapshot:options.includeSnapshot === true ? snapshot : null};}

  window.BaseLocalAPI = {version:VERSION,getSnapshot:getSnapshot,writeSnapshot:writeSnapshot,getPeriods:function(){return getPeriods(getSnapshot());},getStudents:function(periodId, search, estadoMatricula, division){var rows = getStudents(periodId, search, estadoMatricula, getSnapshot());return division ? rows.filter(function(r){return norm(divisionOf(r)) === norm(division);}) : rows;},getStudentsPage:function(periodId, search, estadoMatricula, options){return getStudentsPage(periodId, search, estadoMatricula, options || {}, getSnapshot());},getHistory:function(){return getHistory(getSnapshot());},getDiagnostics:function(){return getDiagnostics(getSnapshot({force:true}));},buildView:buildView,getDivisions:function(periodId){return getDivisions(periodId, getSnapshot());},getDivisionsWithEmpty:function(periodId){return getDivisionsWithEmpty(periodId, getSnapshot());},getAvailableDivisionCareers:function(periodId){return getAvailableDivisionCareers(periodId, getSnapshot());},getDivisionsSummary:function(periodId){return getDivisionsSummary(periodId, getSnapshot());},getDivisionDetail:function(periodId, divisionName){return getDivisionDetail(periodId, divisionName, getSnapshot());},createDivision:createDivision,applyDivisionToCareers:applyDivisionToCareers,replaceDivisionToCareers:replaceDivisionToCareers,deleteDivision:deleteDivision,clearSnapshotCache:clearSnapshotCache,status:function(){var snap=getSnapshot();return {ok:true, mode:"baselocal_core_screen_safe", version:VERSION, students:(snap.students||[]).length, periods:(snap.periods||[]).length, cachedAt:snapshotCache.cachedAt, bl2Estudiantes:!!studentsRepo(), bl2Periodos:!!periodsRepo(), updatedAt:now()};}};
})(window);
