/* =========================================================
Nombre completo: baselocal.app.js
Ruta o ubicación: /Requisitos/BaseLocal/baselocal.app.js
Función o funciones:
- Renderizar Base Local con reglas true/false de carga.
- Cargar períodos al inicio, estudiantes solo en la pestaña Estudiantes.
- Pedir solo la página visible desde BL2/IndexedDB.
- Evitar diagnóstico profundo, Firebase, historial y divisiones pesadas fuera de su pestaña.
========================================================= */
(function(window, document){
  "use strict";

  var VERSION = "2.0.0-screen-page-first";
  var AUTO_SYNC_KEY = "REQ_BL_AUTO_SYNC_ENABLED_V1";
  var state = {tab:"periodos",periodId:"",divisionFilter:"",search:"",statusFilter:"ACTIVO",studentPage:1,studentPageSize:100,loading:false,dailyStarted:false,scriptsReady:false,renderTimer:null,renderSeq:0,lastView:null,lastDashboard:null,lastRenderError:"",lastEventName:"",lastEventAt:0};
  var divisionCache = {key:"", rows:[], at:0};

  function el(id){return document.getElementById(id);}
  function text(value){return String(value == null ? "" : value).trim();}
  function norm(value){return text(value).normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, " ").trim().toLowerCase();}
  function esc(value){return text(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");}
  function status(message, className){var box = el("bl-status");if(box){box.textContent = message;box.className = "bl-status " + (className || "bl-status-info");}}
  function autoSyncAllowed(){try{return localStorage.getItem(AUTO_SYNC_KEY) === "true";}catch(error){return false;}}
  function safe(label, fn, fallback){try{return typeof fn === "function" ? fn() : fallback;}catch(error){console.warn("[BaseLocal " + label + "]", error);state.lastRenderError = error && error.message ? error.message : String(error);return fallback;}}

  function rules(){return {loadPeriods:true,loadStudents:state.tab === "estudiantes",loadStudentPageOnly:true,loadStatusCounts:false,loadHistory:state.tab === "historial",loadDiagnostics:state.tab === "diagnostico",loadDivisions:state.tab === "diagnostico" || (state.tab === "estudiantes" && !!state.periodId),loadFirebase:false,runSync:false,runDeepDashboard:state.tab === "diagnostico"};}
  function currentDir(){try{return new URL(".", document.currentScript ? document.currentScript.src : window.location.href).href;}catch(error){return "";}}
  function hasScript(srcPart){var scripts = document.getElementsByTagName("script");var clean = srcPart.replace(/^\.\.\//, "");for(var i=0;i<scripts.length;i+=1){var src = scripts[i].src || "";if(src.indexOf(srcPart) >= 0 || src.indexOf(clean) >= 0){return true;}}return false;}
  function loadScript(rel){return new Promise(function(resolve){if(hasScript(rel)){resolve(true);return;}var script=document.createElement("script");script.src=new URL(rel,currentDir()).href;script.async=false;script.onload=function(){resolve(true);};script.onerror=function(){console.warn("[BaseLocal] No se pudo cargar", rel);resolve(false);};document.head.appendChild(script);});}
  function ensureOptimizerScripts(){if(state.scriptsReady){return Promise.resolve(true);}var scripts=["../BaseLocal2/bl2-config.js","../BaseLocal2/bl2-detect-runtime.js","../BaseLocal2/bl2-legacy-adapter.js","../BaseLocal2/db/bl2-schema.js","../BaseLocal2/db/bl2-migrations.js","../BaseLocal2/db/bl2-indexeddb-adapter.js","../BaseLocal2/db/bl2-storage.js","../BaseLocal2/services/bl2-search.service.js","../BaseLocal2/services/bl2-pagination.service.js","../BaseLocal2/repositories/bl2-periodos.repo.js","../BaseLocal2/repositories/bl2-estudiantes.repo.js"];var chain=Promise.resolve(true);scripts.forEach(function(rel){chain=chain.then(function(){return loadScript(rel);});});return chain.then(function(){state.scriptsReady=true;try{if(window.BL2Storage&&typeof window.BL2Storage.initialize==="function"){window.BL2Storage.initialize({force:false});}}catch(error){}return true;});}

  function getField(row,name,fallback){try{if(window.BLCampos&&typeof window.BLCampos.getValue==="function"){var value=window.BLCampos.getValue(row||{},name,fallback||"");return text(value)?value:(fallback||"");}}catch(error){}return fallback||"";}
  function pick(row, aliases, fallback){row=row||{};aliases=aliases||[];var keys=Object.keys(row), wanted=aliases.map(function(a){return norm(a).replace(/[^a-z0-9]/g,"");});for(var i=0;i<aliases.length;i+=1){if(Object.prototype.hasOwnProperty.call(row,aliases[i])&&text(row[aliases[i]])){return row[aliases[i]];}}for(var j=0;j<keys.length;j+=1){if(wanted.indexOf(norm(keys[j]).replace(/[^a-z0-9]/g,""))>=0&&text(row[keys[j]])){return row[keys[j]];}}return fallback||"";}
  function divisionOf(row){try{if(window.BLDivisionesService&&typeof window.BLDivisionesService.studentDivision==="function"){return window.BLDivisionesService.studentDivision(row||{});}}catch(error){}var list=Array.isArray(row&&row.divisiones)?row.divisiones:[];return list[0]||(row&&(row.division||row._bl2Division))||"Sin división";}
  var REQ_COLUMNS=[{key:"academico",label:"Académico",aliases:["Academico","Académico","academico"]},{key:"documentacion",label:"Documentación",aliases:["Documentacion","Documentación","documentacion"]},{key:"financiero",label:"Financiero",aliases:["Financiero","financiero"]},{key:"practicasvinculacion",label:"Prácticas",aliases:["PrácticasVinculacion","PracticasVinculacion","practicasvinculacion"]},{key:"vinculacion",label:"Vinculación",aliases:["Vinculacion","Vinculación","vinculacion"]},{key:"seguimientograduados",label:"Seguimiento",aliases:["SeguimientoGraduados","seguimientograduados"]},{key:"ingles",label:"Inglés",aliases:["Ingles","Inglés","ingles"]},{key:"actualizaciondatos",label:"Actualización",aliases:["ActualizaciónDatos","ActualizacionDatos","actualizaciondatos"]},{key:"titulacion",label:"Titulación",aliases:["Titulacion","Titulación","titulacion"]},{key:"aprobaciontitulacion",label:"Aprob. titulación",aliases:["AprobacionTitulacion","AprobaciónTitulacion","aprobaciontitulacion"]},{key:"aprobacioncomplexivoproyecto",label:"Aprob. complexivo",aliases:["AprobacionComplexivoProyecto","AprobaciónComplexivoProyecto","aprobacioncomplexivoproyecto"]}];
  function reqValue(row,req){try{if(window.BL2RequirementsEngine&&typeof window.BL2RequirementsEngine.valueOf==="function"){var v=window.BL2RequirementsEngine.valueOf(row||{},req.key);if(text(v)){return v;}}}catch(error){}try{if(window.BL2StudentNormalizer&&typeof window.BL2StudentNormalizer.value==="function"){var n=window.BL2StudentNormalizer.value(row||{},req.key);if(text(n)){return n;}}}catch(error){}try{if(window.BLCampos&&typeof window.BLCampos.getValue==="function"){var c=window.BLCampos.getValue(row||{},req.key,"");if(text(c)){return c;}}}catch(error){}return pick(row,[req.key].concat(req.aliases||[]),"");}
  function reqEstado(value){try{if(window.BL2RequirementsEngine&&typeof window.BL2RequirementsEngine.cellStatus==="function"){return window.BL2RequirementsEngine.cellStatus(value);}}catch(error){}var k=norm(value);return ["cumple","si","sí","s","ok","aprobado","aprobada","1","true","x","validado","validada","completo","completa"].indexOf(k)>=0?"cumple":"no_cumple";}
  function reqBadge(row,req){var value=reqValue(row,req);var ok=reqEstado(value)==="cumple";return '<span class="bl-req-mini '+(ok?'bl-req-ok':'bl-req-bad')+'" title="'+esc(value||'VACÍO')+'">'+(ok?'CUMPLE':'NO CUMPLE')+'</span>';}

  function currentOffset(){return (Math.max(1,state.studentPage)-1)*state.studentPageSize;}
  function pageInfo(total){var pages=Math.max(1,Math.ceil((total||0)/state.studentPageSize));state.studentPage=Math.max(1,Math.min(state.studentPage,pages));var from=total?currentOffset()+1:0;var to=Math.min(currentOffset()+state.studentPageSize,total||0);return {page:state.studentPage,pages:pages,from:from,to:to,total:total||0,offset:currentOffset(),hasPrev:state.studentPage>1,hasNext:state.studentPage<pages,label:total?(from+"-"+to+" de "+total):"0 registros"};}
  function renderStudentPagination(info){var label=el("bl-students-page-label");if(label){label.textContent=info.label+" · Página "+info.page+" de "+info.pages;}[["bl-students-first",!info.hasPrev],["bl-students-prev",!info.hasPrev],["bl-students-next",!info.hasNext],["bl-students-last",!info.hasNext]].forEach(function(pair){var btn=el(pair[0]);if(btn){btn.disabled=!!pair[1];}});}

  async function getPeriodsFastAsync(){if(window.BL2PeriodosRepo&&typeof window.BL2PeriodosRepo.listarAsync==="function"){try{return await window.BL2PeriodosRepo.listarAsync({force:false});}catch(error){console.warn("[BaseLocal periodos async]",error);}}return safe("periodos",function(){if(window.BL2PeriodosRepo&&typeof window.BL2PeriodosRepo.listar==="function"){return window.BL2PeriodosRepo.listar()||[];}if(window.BaseLocalAPI&&typeof window.BaseLocalAPI.getPeriods==="function"){return window.BaseLocalAPI.getPeriods()||[];}return [];},[]);}
  async function getDivisionsFastAsync(periodId){var r=rules();if(!r.loadDivisions){return [];}var key=text(periodId||"todos");if(divisionCache.key===key&&Date.now()-divisionCache.at<5000){return divisionCache.rows.slice();}var rows=[];try{if(window.BL2EstudiantesRepo&&typeof window.BL2EstudiantesRepo.listDivisionsAsync==="function"){rows=await window.BL2EstudiantesRepo.listDivisionsAsync({periodoId:periodId||"",limit:5000,allowLarge:true});}else if(window.BL2EstudiantesRepo&&typeof window.BL2EstudiantesRepo.listDivisions==="function"){rows=window.BL2EstudiantesRepo.listDivisions({periodoId:periodId||"",limit:5000,allowLarge:true})||[];}else if(window.BaseLocalAPI&&typeof window.BaseLocalAPI.getDivisionsWithEmpty==="function"){rows=window.BaseLocalAPI.getDivisionsWithEmpty(periodId||"")||[];}}catch(error){console.warn("[BaseLocal divisiones]",error);rows=[];}divisionCache={key:key,rows:rows,at:Date.now()};return rows.slice();}
  async function getStudentsFastAsync(){var options={periodoId:state.periodId,periodId:state.periodId,search:state.search,q:state.search,estadoMatricula:state.statusFilter,matricula:state.statusFilter,division:state.divisionFilter,offset:currentOffset(),limit:state.studentPageSize,countTotal:true};if(window.BL2EstudiantesRepo&&typeof window.BL2EstudiantesRepo.listarPaginaAsync==="function"){try{return await window.BL2EstudiantesRepo.listarPaginaAsync(options);}catch(error){console.warn("[BaseLocal BL2 async]",error);}}if(window.BL2&&window.BL2.estudiantes&&typeof window.BL2.estudiantes.listarPaginaAsync==="function"){try{return await window.BL2.estudiantes.listarPaginaAsync(options);}catch(error2){console.warn("[BaseLocal BL2 API async]",error2);}}if(window.BaseLocalAPI&&typeof window.BaseLocalAPI.getStudentsPage==="function"){return window.BaseLocalAPI.getStudentsPage(state.periodId,state.search,state.statusFilter,{division:state.divisionFilter,offset:currentOffset(),limit:state.studentPageSize,countTotal:true});}return {rows:[],total:0,offset:currentOffset(),limit:state.studentPageSize,source:"sin_fuente"};}
  async function buildViewAsync(){var r=rules();var periods=r.loadPeriods?await getPeriodsFastAsync():[];var divisions=await getDivisionsFastAsync(state.periodId);var view={periods:periods,students:[],renderStudents:[],studentsPage:{total:0,offset:currentOffset(),limit:state.studentPageSize,source:"none"},totalStudentsVisible:0,statusCounts:{ACTIVO:0,RETIRADO:0,TOTAL:0},history:[],historyCount:0,diagnostics:{ok:true,lazy:true},careersCount:0,divisions:divisions,snapshot:null,rules:r};if(r.loadStudents){var result=await getStudentsFastAsync();var rows=Array.isArray(result.rows)?result.rows:[];var total=Number(result.total==null?rows.length:result.total)||0;var info=pageInfo(total);view.renderStudents=rows;view.students=rows.slice();view.studentsPage={total:total,offset:info.offset,limit:state.studentPageSize,source:result.source||"BL2"};view.totalStudentsVisible=total;view.statusCounts={ACTIVO:state.statusFilter==="ACTIVO"?total:0,RETIRADO:state.statusFilter==="RETIRADO"?total:0,TOTAL:total};view.careersCount=safe("carrerasPagina",function(){var map={};rows.forEach(function(row){var c=text(row.nombreCarrera||row.nombrecarrera||row._bl2Carrera||row.Carrera||"");if(c){map[norm(c)]=true;}});return Object.keys(map).length;},0);}if(r.loadHistory){view.history=safe("historial",function(){return window.BaseLocalAPI&&typeof window.BaseLocalAPI.getHistory==="function"?window.BaseLocalAPI.getHistory().slice(0,50):[];},[]);view.historyCount=view.history.length;}if(r.loadDiagnostics){view.diagnostics=safe("diagnostico",function(){return window.BaseLocalAPI&&typeof window.BaseLocalAPI.getDiagnostics==="function"?window.BaseLocalAPI.getDiagnostics():{ok:true,lazy:true};},{ok:false,error:"Diagnóstico no disponible"});}return view;}

  function dashboard(deep){if(!deep){return null;}return safe("dashboard",function(){if(window.BL2DashboardRepo&&typeof window.BL2DashboardRepo.summary==="function"){return window.BL2DashboardRepo.summary({periodId:state.periodId,deep:true});}if(window.BaseLocalBridge&&typeof window.BaseLocalBridge.counts==="function"){var c=window.BaseLocalBridge.counts({light:true});return {periods:(c.snapshot&&c.snapshot.periods)||0,students:(c.snapshot&&c.snapshot.students)||0,history:(c.byCollection&&c.byCollection.historial)||0,statusCounts:{}};}return null;},null);}
  function table(headers,rows){if(!rows||!rows.length){return '<p class="bl-help">Sin datos todavía.</p>';}var html='<table><thead><tr>'+headers.map(function(h){return '<th>'+esc(h.label)+'</th>';}).join("")+'</tr></thead><tbody>';html+=rows.map(function(row){return '<tr>'+headers.map(function(h){var value=typeof h.value==="function"?h.value(row):row[h.key];return '<td>'+esc(value)+'</td>';}).join("")+'</tr>';}).join("");return html+'</tbody></table>';}
  function renderPeriods(view){var target=el("bl-periodos-table");if(target){target.innerHTML=table([{label:"Período",key:"label"},{label:"ID",key:"id"},{label:"Actualizado",key:"updatedAt"}],view.periods||[]);}}
  function renderStudents(view){var target=el("bl-estudiantes-table");if(!target){return;}var rows=view.renderStudents||[];var info=pageInfo(view.totalStudentsVisible||0);renderStudentPagination(info);if(!rows.length){target.innerHTML='<p class="bl-help">Sin estudiantes visibles. Revisa período, estado, división o búsqueda.</p>';return;}var headers=["Cédula","Nombre","Carrera","División","Sede","Estado","Período"].concat(REQ_COLUMNS.map(function(req){return req.label;})).concat(["Acciones"]);var html='<table><thead><tr>'+headers.map(function(label){return '<th>'+esc(label)+'</th>';}).join("")+'</tr></thead><tbody>';html+=rows.map(function(row,index){var cells=[esc(row.cedula||row._bl2Id||getField(row,"cedula","")),esc(row.nombres||row._bl2Nombre||getField(row,"nombres",row.Nombres||"")),esc(row.nombreCarrera||row.nombrecarrera||row._bl2Carrera||getField(row,"nombreCarrera",row.NombreCarrera||"")),esc(divisionOf(row)),esc(getField(row,"sede",row.Sede||row.sede||"")),esc(row.estadoMatricula||row._bl2EstadoMatricula||getField(row,"estadoMatricula","ACTIVO")),esc(row.periodoLabel||row._bl2Periodo||row.periodoId||getField(row,"periodoId",""))];var reqCells=REQ_COLUMNS.map(function(req){return reqBadge(row,req);});var inspect='<button type="button" class="bl-btn bl-btn-light bl-btn-see-more" data-bl-student-json="'+index+'" data-bl-student-detail="'+index+'">Ver más</button>';return '<tr>'+cells.map(function(value){return '<td>'+value+'</td>';}).join("")+reqCells.map(function(value){return '<td>'+value+'</td>';}).join("")+'<td>'+inspect+'</td></tr>';}).join("");target.innerHTML=html+'</tbody></table>';try{if(window.BaseLocalStudentDetail&&typeof window.BaseLocalStudentDetail.refreshButtons==="function"){window.BaseLocalStudentDetail.refreshButtons();}}catch(error){}}
  function renderHistory(view){var target=el("bl-history-table");if(target){target.innerHTML=table([{label:"Fecha",key:"createdAt"},{label:"Acción",value:function(row){return row.action||"análisis";}},{label:"Período",key:"periodoLabel"},{label:"Origen",key:"fileName"},{label:"Filas",key:"totalRows"}],view.history||[]);}}
  function renderDiagnostics(view){var box=el("bl-diagnostics-box");if(!box){return;}var firebaseStatus=safe("firebaseStatus",function(){return window.BaseLocalFirebase&&typeof window.BaseLocalFirebase.getLastStatus==="function"?window.BaseLocalFirebase.getLastStatus():{ok:false,mode:"sin_firebase"};},{ok:false,mode:"sin_firebase"});var syncStatus=safe("syncStatus",function(){return window.BaseLocalFirebase&&typeof window.BaseLocalFirebase.getSyncStatus==="function"?window.BaseLocalFirebase.getSyncStatus():{ok:false,mode:"sin_sync"};},{ok:false,mode:"sin_sync"});var bridgeCounts=safe("bridgeCounts",function(){return window.BaseLocalBridge&&typeof window.BaseLocalBridge.counts==="function"?window.BaseLocalBridge.counts({light:true}):null;},null);box.textContent=JSON.stringify({dashboard:state.lastDashboard,local:view.diagnostics||{},vista:{periodoId:state.periodId,division:state.divisionFilter,estadoMatricula:state.statusFilter,busqueda:state.search,estudiantesVisibles:(view.renderStudents||[]).length,estudiantesTotal:view.totalStudentsVisible||0,studentsSource:view.studentsPage&&view.studentsPage.source},firebase:firebaseStatus,sync:syncStatus,bridge:bridgeCounts,ultimoErrorVista:state.lastRenderError||"",reglas:view.rules,rendimiento:{version:VERSION,tab:state.tab,panelLiviano:true,paginacionReal:true,scriptsReady:state.scriptsReady}},null,2);}
  function renderSelectors(view){var selector=el("bl-filter-period");if(selector){var current=state.periodId||selector.value;selector.innerHTML='<option value="">Todos los períodos</option>'+(view.periods||[]).map(function(period){return '<option value="'+esc(period.id)+'">'+esc(period.label||period.id)+'</option>';}).join("");selector.value=current;}var estado=el("bl-filter-estado");if(estado){estado.value=state.statusFilter;}var div=el("bl-filter-division");if(div){var divisions=view.divisions||[];var currentDivision=state.divisionFilter;div.innerHTML='<option value="">Todas</option>'+divisions.map(function(name){return '<option value="'+esc(name)+'">'+esc(name)+'</option>';}).join("");if(currentDivision&&divisions.length&&divisions.indexOf(currentDivision)<0){state.divisionFilter="";div.value="";}else{div.value=currentDivision;}}}
  function renderActiveTab(view){if(state.tab==="periodos"){renderPeriods(view);return;}if(state.tab==="estudiantes"){renderStudents(view);return;}if(state.tab==="historial"){renderHistory(view);return;}if(state.tab==="diagnostico"){renderDiagnostics(view);return;}if(state.tab==="manual"){var manual=el("bl-manual-text");if(manual&&window.BaseLocalManual){manual.value=window.BaseLocalManual.getManual();}}}
  function renderKpis(view,dash,firebaseStatus,syncStatus){var total=view.statusCounts&&view.statusCounts.TOTAL?view.statusCounts.TOTAL:(dash&&dash.students!=null?dash.students:0);if(el("bl-kpi-periodos")){el("bl-kpi-periodos").textContent=dash&&dash.periods!=null?dash.periods:(view.periods||[]).length;}if(el("bl-kpi-estudiantes")){el("bl-kpi-estudiantes").textContent=total||0;}if(el("bl-kpi-activos")){el("bl-kpi-activos").textContent=view.statusCounts&&view.statusCounts.ACTIVO?view.statusCounts.ACTIVO:((dash&&dash.statusCounts&&dash.statusCounts.ACTIVO)||"—");}if(el("bl-kpi-retirados")){el("bl-kpi-retirados").textContent=view.statusCounts&&view.statusCounts.RETIRADO?view.statusCounts.RETIRADO:((dash&&dash.statusCounts&&dash.statusCounts.RETIRADO)||"—");}if(el("bl-kpi-historial")){el("bl-kpi-historial").textContent=dash&&dash.history!=null?dash.history:(view.historyCount||0);}if(el("bl-kpi-carreras")){el("bl-kpi-carreras").textContent=view.careersCount||(dash&&dash.careers!=null?dash.careers:"—");}if(el("bl-kpi-estado")){el("bl-kpi-estado").textContent=syncStatus&&syncStatus.ok?"Sincronizada":(firebaseStatus&&firebaseStatus.ok?"Firebase":"Local");}}
  async function render(){var seq=++state.renderSeq;try{var view=await buildViewAsync();if(seq!==state.renderSeq){return;}state.lastView=view;state.lastDashboard=dashboard(rules().runDeepDashboard);var firebaseStatus=state.tab==="diagnostico"?safe("firebaseStatus",function(){return window.BaseLocalFirebase&&typeof window.BaseLocalFirebase.getLastStatus==="function"?window.BaseLocalFirebase.getLastStatus():null;},null):null;var syncStatus=state.tab==="diagnostico"?safe("syncStatus",function(){return window.BaseLocalFirebase&&typeof window.BaseLocalFirebase.getSyncStatus==="function"?window.BaseLocalFirebase.getSyncStatus():null;},null):null;renderSelectors(view);renderKpis(view,state.lastDashboard,firebaseStatus,syncStatus);renderActiveTab(view);if(!state.loading){status("Base Local rápida. Pestaña: "+state.tab+". Registros visibles: "+((view.renderStudents||[]).length)+" de "+(view.totalStudentsVisible||0)+".","bl-status-ok");}}catch(error){console.error("[BaseLocal Render]",error);state.lastRenderError=error&&error.message?error.message:String(error);var fallback={periods:[],renderStudents:[],students:[],divisions:[],totalStudentsVisible:0,statusCounts:{TOTAL:0},history:[],diagnostics:{ok:false,error:state.lastRenderError},rules:rules()};state.lastView=fallback;renderSelectors(fallback);renderActiveTab(fallback);status("Base Local no se cayó. Error controlado: "+state.lastRenderError,"bl-status-warn");}}
  function invalidateCaches(){divisionCache={key:"",rows:[],at:0};safe("invalidate",function(){if(window.BaseLocalAPI&&typeof window.BaseLocalAPI.clearSnapshotCache==="function"){window.BaseLocalAPI.clearSnapshotCache();}if(window.RequisitosBL&&typeof window.RequisitosBL.invalidate==="function"){window.RequisitosBL.invalidate();}if(window.BL2EstudiantesRepo&&typeof window.BL2EstudiantesRepo.invalidate==="function"){window.BL2EstudiantesRepo.invalidate();}if(window.BL2PeriodosRepo&&typeof window.BL2PeriodosRepo.invalidate==="function"){window.BL2PeriodosRepo.invalidate();}if(window.BL2DashboardRepo&&typeof window.BL2DashboardRepo.invalidate==="function"){window.BL2DashboardRepo.invalidate();}},null);}
  function scheduleRender(reason,delay){if(state.renderTimer){clearTimeout(state.renderTimer);}state.renderTimer=setTimeout(function(){state.renderTimer=null;render(reason||"programado");},delay==null?180:delay);}
  function setTab(tab){state.tab=tab;if(tab!=="estudiantes"){state.studentPage=1;}document.querySelectorAll(".bl-tabs button").forEach(function(button){button.classList.toggle("is-active",button.dataset.tab===tab);});document.querySelectorAll(".bl-panel").forEach(function(panel){panel.classList.toggle("is-active",panel.id==="bl-tab-"+tab);});scheduleRender("tab-"+tab);}
  function setBusy(isBusy,message,mode){state.loading=!!isBusy;var map={"bl-btn-pull-firebase":["Solo bajar Firebase","Bajando...","pull"],"bl-btn-sync-now":["Sincronizar ahora","Sincronizando...","sync"],"bl-btn-clean-base":["Limpiar base","Limpiando...","clean"],"bl-btn-delete-period":["Borrar período","Borrando...","delete"]};Object.keys(map).forEach(function(id){var btn=el(id);if(btn){btn.disabled=!!isBusy;btn.textContent=isBusy&&map[id][2]===mode?map[id][1]:map[id][0];}});if(message){status(message,"bl-status-info");}}
  function exportJson(){try{var data=window.BaseLocalAPI&&typeof window.BaseLocalAPI.getSnapshot==="function"?window.BaseLocalAPI.getSnapshot({force:false}):(window.BaseLocalBridge&&window.BaseLocalBridge.getSnapshot?window.BaseLocalBridge.getSnapshot({force:false}):{});var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});var link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="carga-base-local.json";link.click();setTimeout(function(){URL.revokeObjectURL(link.href);},1000);}catch(error){status("No se pudo exportar Base Local: "+(error.message||error),"bl-status-warn");}}
  function copyRefs(){var content=window.BaseLocalManual?window.BaseLocalManual.getManual():"";if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(content).then(function(){status("Referencias copiadas.","bl-status-ok");}).catch(function(){status("Copia manualmente desde la pestaña Manual.","bl-status-warn");});return;}status("Copia manualmente desde la pestaña Manual.","bl-status-warn");}
  async function pullFromFirebase(){if(state.loading){return;}try{if(!window.BaseLocalFirebase||typeof window.BaseLocalFirebase.pull!=="function"){throw new Error("BaseLocalFirebase no está disponible.");}setBusy(true,"Bajando datos desde Firebase hacia la base local...","pull");var result=await window.BaseLocalFirebase.pull({mode:"manual_pull",full:true});state.periodId="";state.divisionFilter="";state.search="";state.statusFilter="ACTIVO";state.studentPage=1;["bl-filter-search","bl-filter-division"].forEach(function(id){if(el(id)){el(id).value="";}});if(el("bl-filter-estado")){el("bl-filter-estado").value="ACTIVO";}invalidateCaches();await render();status("Datos bajados correctamente desde Firebase. Estudiantes: "+(result.totalStudents||0)+". Períodos: "+(result.totalPeriods||0)+".","bl-status-ok");}catch(error){status("Base Local sigue activa. Error al bajar Firebase: "+(error.message||String(error)),"bl-status-warn");}finally{setBusy(false);}}
  async function syncNow(mode){if(state.loading){return;}try{if(!window.BaseLocalFirebase||typeof window.BaseLocalFirebase.sync!=="function"){throw new Error("BaseLocalFirebase.sync no está disponible.");}setBusy(true,"Sincronizando Base Local con Firebase...","sync");var result=await window.BaseLocalFirebase.sync({mode:mode||"manual",full:false});invalidateCaches();await render();status(result&&result.ok?(result.message||"Sincronización finalizada correctamente."):((result&&result.message)||"No se pudo sincronizar. Base Local sigue funcionando."),result&&result.ok?"bl-status-ok":"bl-status-warn");}catch(error){status("Base Local sigue activa. Error de sincronización: "+(error.message||String(error)),"bl-status-warn");}finally{setBusy(false);}}
  async function limpiarBase(){if(state.loading){return;}try{if(!window.BaseLocalLimpiar||typeof window.BaseLocalLimpiar.ejecutar!=="function"){throw new Error("BaseLocalLimpiar no está disponible.");}setBusy(true,"Limpiando Firebase y reconstruyendo Base Local...","clean");var result=await window.BaseLocalLimpiar.ejecutar();state.periodId="";state.divisionFilter="";state.search="";state.statusFilter="ACTIVO";state.studentPage=1;invalidateCaches();await render();status((result&&result.mensaje)||"Firebase y Base Local reparados.",result&&result.errores&&result.errores.length?"bl-status-warn":"bl-status-ok");}catch(error){status("Base Local sigue activa. Error al limpiar base: "+(error.message||String(error)),"bl-status-warn");}finally{setBusy(false);}}
  function parentOwnsDailySync(){try{return !!(window.parent&&window.parent!==window&&window.parent.MAQ_BASELOCAL_BACKGROUND_SYNC);}catch(error){return false;}}
  function runDailySync(){if(parentOwnsDailySync()||state.dailyStarted){state.dailyStarted=true;return;}state.dailyStarted=true;if(!autoSyncAllowed()){status("Base Local activa. Sincronización automática pausada para mantener la pantalla rápida.","bl-status-ok");return;}setTimeout(async function(){try{if(!window.BaseLocalFirebase||typeof window.BaseLocalFirebase.runDailyIfNeeded!=="function"){return;}var result=await window.BaseLocalFirebase.runDailyIfNeeded(false,{mode:"daily_from_bl",background:true});if(result&&result.ok){invalidateCaches();render();status(result.message||"Sincronización diaria completada en segundo plano.","bl-status-ok");}}catch(error){status("Base Local activa. Firebase queda pendiente: "+(error.message||error),"bl-status-warn");}},3200);}
  function eventAllowed(name){var at=Date.now();if(state.lastEventName===name&&at-state.lastEventAt<450){return false;}state.lastEventName=name;state.lastEventAt=at;return true;}
  function bindCrossWindowEvents(){window.addEventListener("storage",function(event){if(event.key==="REQ_BL_SIGNAL_V1"&&eventAllowed("storage")){invalidateCaches();scheduleRender("storage",260);}});window.addEventListener("message",function(event){var type=String((event.data||{}).type||"");if(type.indexOf("requisitos:bl:")===0&&eventAllowed(type)){invalidateCaches();scheduleRender(type,260);}});["requisitos:bl:changed","requisitos:bl:snapshot-changed","requisitos:bl:sync-complete","baselocal:sync-complete","baselocal:firebase-pull-finished","requisitos:bl:mirror-complete","requisitos:bl:limpieza-complete","requisitos:bl:periodo-borrado","baselocal:periodo-borrado","requisitos:bl:division-created","requisitos:bl:periodo-borrado-historial-purgado"].forEach(function(name){window.addEventListener(name,function(){if(eventAllowed(name)){invalidateCaches();scheduleRender(name,260);}});});}
  function bindGlobalErrors(){window.addEventListener("error",function(event){state.lastRenderError=event&&event.message?event.message:"Error de pantalla Base Local";status("Base Local protegida. Error controlado: "+state.lastRenderError,"bl-status-warn");});window.addEventListener("unhandledrejection",function(event){var reason=event&&event.reason?event.reason:"Promesa rechazada";state.lastRenderError=reason&&reason.message?reason.message:String(reason);status("Base Local protegida. Error de sincronización controlado: "+state.lastRenderError,"bl-status-warn");});}
  window.BaseLocalApp={version:VERSION,render:render,scheduleRender:scheduleRender,status:status,setBusy:setBusy,getState:function(){return Object.assign({},state,{rules:rules()});}};
  function boot(){bindGlobalErrors();safe("ExcelLocalBridge.ensureReady",function(){if(window.ExcelLocalBridge&&typeof window.ExcelLocalBridge.ensureReady==="function"){window.ExcelLocalBridge.ensureReady();}},null);document.querySelectorAll(".bl-tabs button").forEach(function(button){button.addEventListener("click",function(){setTab(button.dataset.tab);});});if(el("bl-filter-period")){el("bl-filter-period").addEventListener("change",function(event){state.periodId=event.target.value;state.divisionFilter="";state.studentPage=1;invalidateCaches();scheduleRender("period-filter");});}if(el("bl-filter-estado")){el("bl-filter-estado").addEventListener("change",function(event){state.statusFilter=event.target.value;state.studentPage=1;scheduleRender("estado-filter");});}if(el("bl-filter-division")){el("bl-filter-division").addEventListener("change",function(event){state.divisionFilter=event.target.value;state.studentPage=1;scheduleRender("division-filter");});}if(el("bl-filter-search")){el("bl-filter-search").addEventListener("input",function(event){state.search=event.target.value;state.studentPage=1;scheduleRender("search",520);});}if(el("bl-btn-refresh")){el("bl-btn-refresh").addEventListener("click",function(){invalidateCaches();render();});}if(el("bl-btn-pull-firebase")){el("bl-btn-pull-firebase").addEventListener("click",pullFromFirebase);}if(el("bl-btn-sync-now")){el("bl-btn-sync-now").addEventListener("click",function(){syncNow("manual");});}if(el("bl-btn-clean-base")){el("bl-btn-clean-base").addEventListener("click",limpiarBase);}if(el("bl-btn-export")){el("bl-btn-export").addEventListener("click",exportJson);}if(el("bl-btn-copy-refs")){el("bl-btn-copy-refs").addEventListener("click",copyRefs);}if(el("bl-students-first")){el("bl-students-first").addEventListener("click",function(){state.studentPage=1;render();});}if(el("bl-students-prev")){el("bl-students-prev").addEventListener("click",function(){state.studentPage=Math.max(1,state.studentPage-1);render();});}if(el("bl-students-next")){el("bl-students-next").addEventListener("click",function(){state.studentPage+=1;render();});}if(el("bl-students-last")){el("bl-students-last").addEventListener("click",function(){var total=(state.lastView&&(state.lastView.totalStudentsVisible||state.lastView.studentsPage&&state.lastView.studentsPage.total))||0;state.studentPage=Math.max(1,Math.ceil(total/state.studentPageSize));render();});}bindCrossWindowEvents();status("Inicializando reglas rápidas de Base Local...","bl-status-info");ensureOptimizerScripts().then(function(){render();try{window.dispatchEvent(new CustomEvent("bl:ready",{detail:{module:"BaseLocal",ready:true,version:VERSION,at:new Date().toISOString()}}));if(window.parent&&window.parent!==window){window.parent.postMessage({type:"requisitos:bl:ready",payload:{module:"BaseLocal",ready:true,version:VERSION,at:new Date().toISOString()}},"*");}}catch(error){}runDailySync();});}
  if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",boot);}else{boot();}
})(window, document);
