/* Acciones compactas para Tabla: mensajes, contadores y canales */
(function(window,document){
  "use strict";
  var TYPES=[["requisitos","Falta req."],["urgente","Urgente"],["ultimo","Último aviso"],["regularizar","Regularizar"],["nota_articulo","Falta N-Art"],["nota_defensa","Falta N-Def"],["sin_articulo","Sin artículo"],["no_aprueba","No aprueba"],["perdio","Perdió"],["alerta","Alerta"],["libre","Personal"]];
  var loaded={};
  function el(id){return document.getElementById(id);}function text(v){return String(v==null?"":v).trim();}function esc(v){return text(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}function status(m,c){var b=el("tabla-status");if(b){b.textContent=m;b.className="tabla-status "+(c||"");}}
  function load(src){if(loaded[src]||document.querySelector('script[data-tabla-actions="'+src+'"],script[data-tabla-lazy="'+src+'"]')){loaded[src]=true;return Promise.resolve();}return new Promise(function(ok,no){var s=document.createElement("script");s.src=src;s.async=false;s.setAttribute("data-tabla-actions",src);s.onload=function(){loaded[src]=true;ok();};s.onerror=function(){no(new Error("No se pudo cargar "+src));};document.body.appendChild(s);});}
  function loads(list){return (list||[]).reduce(function(p,src){return p.then(function(){return load(src);});},Promise.resolve());}function needBase(){return loads(["tabla.message.js","tabla.history.js"]);}function needTelegram(){return loads(["tabla.message.js","tabla.history.js","tabla.telegram-api.js","tabla.telegram.js"]);}
  function state(){return window.TablaApp&&TablaApp.getState?TablaApp.getState():{rows:[]};}function rowIndexFromNode(node){var tr=node&&node.closest?node.closest("tr"):null;if(!tr)return -1;return Array.prototype.indexOf.call(tr.parentNode.children,tr);}function rowFor(node){var i=rowIndexFromNode(node);return (state().rows||[])[i]||null;}function tipoFor(node){var tr=node&&node.closest?node.closest("tr"):null;var sel=tr?tr.querySelector(".tabla-message-select"):null;return sel?sel.value:"requisitos";}
  function option(v,l,s){return '<option value="'+esc(v)+'" '+(s?'selected':'')+'>'+esc(l)+'</option>';}function fillSelect(sel){if(!sel||sel.getAttribute("data-actions-ready")==="1")return;sel.innerHTML=TYPES.map(function(p){return option(p[0],p[1],p[0]==="requisitos");}).join("");sel.setAttribute("data-actions-ready","1");}
  function counts(row){return window.TablaHistory&&TablaHistory.countsForStudent?TablaHistory.countsForStudent(row):{wa:0,tg:0,email:0,whatsapp:0,telegram:0,mail:0};}function last(row){return window.TablaHistory&&TablaHistory.lastLabel?TablaHistory.lastLabel(row):"—";}function btn(channel,count,disabled){var cls=channel==="WA"?"action-whats":(channel==="TG"?"action-telegram":"action-mail");return '<button class="tabla-channel '+cls+'" type="button" '+(disabled?'disabled ':'')+'data-action-channel="'+esc(channel)+'">'+esc(channel)+' <small>'+esc(count)+'</small></button>';}
  function enhance(){var wrap=el("tabla-table-wrap");if(!wrap)return;var rows=state().rows||[];Array.prototype.forEach.call(wrap.querySelectorAll("tbody tr"),function(tr,i){var row=rows[i];if(!row)return;fillSelect(tr.querySelector(".tabla-message-select"));var c=counts(row);var lastCell=tr.children[4];if(lastCell)lastCell.innerHTML='<span class="tabla-last-message" title="'+esc(last(row))+'">'+esc(last(row))+'</span>';if(tr.children[5])tr.children[5].innerHTML=btn('WA',c.wa||c.whatsapp||0,!text(row._celular));if(tr.children[6])tr.children[6].innerHTML=btn('TG',c.tg||c.telegram||0,false);if(tr.children[7])tr.children[7].innerHTML=btn('Mail',c.email||c.mail||0,!text(row._correo));});}
  function msg(row,tipo){if(window.TablaMessage&&TablaMessage.generarMensaje)return TablaMessage.generarMensaje(row,tipo,{texto:""});return "Saludos, "+(row._nombres||"estudiante")+". Desde el área de Titulación se informa que existen novedades en su proceso.";}function label(tipo){if(window.TablaMessage&&TablaMessage.tipoLabel)return TablaMessage.tipoLabel(tipo);var f=TYPES.filter(function(x){return x[0]===tipo;})[0];return f?f[1]:tipo;}
  function record(row,channel,tipo,message){if(!window.TablaHistory||!TablaHistory.guardar)return;var d=window.TablaMessage&&TablaMessage.datosEstudiante?TablaMessage.datosEstudiante(row):{};TablaHistory.guardar({canal:channel,modo:"individual",tipoMensaje:tipo,tipoLabel:label(tipo),cedula:d.cedula||row._cedula,nombre:d.nombre||row._nombres,carrera:d.carrera||row._carrera,periodo:d.periodo||row._periodo,correo:d.correo||row._correo,telefono:d.celular||row._celular,telegramUser:row._telegramUser,telegramChatId:row._telegramChatId,mensaje:message,estado:"preparado"});}
  function openWA(row,message){var phone=text(row&&row._celular).replace(/[^0-9]/g,"");if(!phone){status("Sin celular registrado.","warn");return;}if(phone.length===10&&phone.charAt(0)==="0")phone="593"+phone.slice(1);window.open("https://wa.me/"+phone+"?text="+encodeURIComponent(message),"_blank","noopener");}
  function openMail(row,tipo,message){var email=text(row&&row._correo);if(!email){status("Sin correo registrado.","warn");return;}var subject=window.TablaMessage&&TablaMessage.asunto?TablaMessage.asunto(row,tipo):"Proceso de titulación";window.open("mailto:"+encodeURIComponent(email)+"?subject="+encodeURIComponent(subject)+"&body="+encodeURIComponent(message),"_blank","noopener");}
  function handleClick(ev){var btn=ev.target&&ev.target.closest?ev.target.closest("[data-action-channel]"):null;if(!btn||btn.disabled)return;var row=rowFor(btn);if(!row)return;var ch=btn.getAttribute("data-action-channel"),tipo=tipoFor(btn);needBase().then(function(){var message=msg(row,tipo);if(ch==="WA"){record(row,"whatsapp",tipo,message);openWA(row,message);status("WhatsApp preparado.","ok");}else if(ch==="Mail"){record(row,"mail",tipo,message);openMail(row,tipo,message);status("Correo preparado.","ok");}else if(ch==="TG"){record(row,"telegram",tipo,message);needTelegram().then(function(){if(window.TablaTelegram&&TablaTelegram.abrir)TablaTelegram.abrir(row,tipo);});status("Telegram preparado.","ok");}setTimeout(enhance,150);});}
  function boot(){var wrap=el("tabla-table-wrap");if(wrap){wrap.addEventListener("click",handleClick);wrap.addEventListener("change",function(ev){if(ev.target&&ev.target.classList&&ev.target.classList.contains("tabla-message-select"))setTimeout(enhance,80);});var mo=new MutationObserver(function(){needBase().then(enhance).catch(enhance);});mo.observe(wrap,{childList:true,subtree:true});}window.addEventListener("tabla:history-updated",function(){setTimeout(enhance,80);});needBase().then(enhance).catch(enhance);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
  window.TablaActions={enhance:enhance};
})(window,document);
