/* Tabla compacta mínima: filtros visuales y chips */
(function(window,document){
  "use strict";
  var state={periodId:"",division:"",matricula:"ACTIVO",career:"",status:"",search:"",requirements:["falta"],rows:[],allRows:[],page:1,pageSize:100,pagination:null,timer:null,periodKey:"",depKey:"",divisionOptions:[],careerOptions:[]};
  function el(id){return document.getElementById(id);}function text(v){return String(v==null?"":v).trim();}function esc(v){return text(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}function status(m,c){var b=el("tabla-status");if(b){b.textContent=m;b.className="tabla-status "+(c||"");}}function set(id,v){var n=el(id);if(n)n.textContent=v;}function option(v,l,s){return '<option value="'+esc(v)+'" '+(s?'selected':'')+'>'+esc(l)+'</option>';}function source(){return window.TablaCore&&TablaCore.source?TablaCore.source():"Base Local";}
  function loadActions(){if(document.querySelector('script[data-tabla-actions="tabla.actions.js"]'))return;var s=document.createElement("script");s.src="tabla.actions.js";s.async=false;s.setAttribute("data-tabla-actions","tabla.actions.js");document.body.appendChild(s);}
  function pid(i){i=i||{};return typeof i!=="object"?text(i):text(i.id||i.periodoId||i.periodId||i.value||i.key||i.label||i.periodoLabel||i.nombre||i.name);}function plabel(i){i=i||{};return typeof i!=="object"?text(i):text(i.label||i.periodoLabel||i.nombre||i.name||i.descripcion||i.id||i.periodoId||i.periodId||i.value||i.key);}function key(items){return (items||[]).map(function(i){return pid(i)+"::"+plabel(i);}).join("||");}
  function fillPeriods(){var s=el("tabla-periodo"),ps,k;if(!s||!window.TablaCore||!TablaCore.periods)return;ps=TablaCore.periods()||[];k=source()+"|"+key(ps);if(state.periodKey!==k){s.innerHTML=option("","Todos",!state.periodId)+ps.map(function(i){var id=pid(i);return option(id,plabel(i)||id,state.periodId===id);}).join("");state.periodKey=k;}s.value=state.periodId;}
  function fillDeps(){var d=el("tabla-division"),c=el("tabla-carrera"),opts,k=[source(),state.periodId,state.matricula,state.division].join("|");if(state.depKey!==k){opts=window.TablaCore&&TablaCore.options?TablaCore.options({periodId:state.periodId,matricula:state.matricula,division:state.division}):{divisions:[],careers:[]};state.divisionOptions=opts.divisions||[];state.careerOptions=opts.careers||[];state.depKey=k;}if(d){d.innerHTML=option("","Todas",!state.division)+state.divisionOptions.map(function(x){return option(x,x,state.division===x);}).join("");d.value=state.division;}if(c){c.innerHTML=option("","Todas",!state.career)+state.careerOptions.map(function(x){return option(x,x,state.career===x);}).join("");c.value=state.career;}}
  function chips(){var w=el("tabla-req-chips");if(!w)return;Array.prototype.forEach.call(w.querySelectorAll("[data-req-filter]"),function(b){var k=b.getAttribute("data-req-filter");var a=state.requirements.indexOf(k)>=0;b.classList.toggle("is-active",a);b.setAttribute("aria-pressed",a?"true":"false");});}
  function request(reset){if(reset)state.page=1;if(state.timer)clearTimeout(state.timer);state.timer=setTimeout(render,0);}function renderTable(rows){var w=el("tabla-table-wrap"),html;if(!w)return;if(!rows.length){w.innerHTML='<div class="empty">Sin datos.</div>';return;}html='<table><thead><tr><th>Cédula</th><th>Nombre</th><th>Carrera</th><th>Msg</th><th>Último</th><th>WA</th><th>TG</th><th>Mail</th></tr></thead><tbody>';html+=rows.map(function(r){return '<tr><td class="nowrap">'+esc(r._cedula)+'</td><td>'+esc(r._nombres)+'</td><td><span class="tabla-career-short" title="'+esc(r._carrera)+'">'+esc(r._carreraCorta||r._carrera)+'</span></td><td><select class="tabla-message-select"><option>Falta req.</option></select></td><td><span class="tabla-last-message">—</span></td><td><button class="tabla-channel action-whats" type="button">WA <small>0</small></button></td><td><button class="tabla-channel action-telegram" type="button">TG <small>0</small></button></td><td><button class="tabla-channel action-mail" type="button">Mail <small>0</small></button></td></tr>';}).join("");w.innerHTML=html+'</tbody></table>';if(window.TablaActions&&TablaActions.enhance)TablaActions.enhance();}
  function pageButtons(p){state.pagination=p||{page:1,pages:1,total:0,label:"0 registros",hasPrev:false,hasNext:false};set("tabla-count-text",state.pagination.total+" registro(s) filtrados");set("tabla-page-text","Página "+state.pagination.page+" de "+state.pagination.pages);set("tabla-page-label",state.pagination.label);}
  function render(){var r,sum;try{if(!window.TablaCore||!TablaCore.page)throw new Error("TablaCore no disponible.");fillPeriods();fillDeps();chips();r=TablaCore.page({periodId:state.periodId,division:state.division,matricula:state.matricula,career:state.career,status:state.status,search:state.search,page:state.page,pageSize:state.pageSize,requirements:state.requirements});state.rows=r.rows||[];state.allRows=r.allRows||[];sum=r.summary||TablaCore.summary(state.allRows);set("tabla-kpi-total",sum.total||0);set("tabla-kpi-ok",sum.cumple||0);set("tabla-kpi-pend",sum.pendiente||0);set("tabla-kpi-no",sum.no_cumple||0);set("tabla-kpi-carreras",sum.carreras||0);pageButtons(r.pagination);renderTable(state.rows);status("Tabla cargada por "+(r.source||source())+".","ok");}catch(e){status(e.message||String(e),"warn");}}
  function resetDeps(){state.division="";state.career="";state.page=1;state.depKey="";}function bind(id,ev,fn){var n=el(id);if(n)n.addEventListener(ev,fn);}function boot(){loadActions();bind("tabla-periodo","change",function(e){state.periodId=e.target.value;resetDeps();request();});bind("tabla-division","change",function(e){state.division=e.target.value;state.career="";state.page=1;state.depKey="";request();});bind("tabla-carrera","change",function(e){state.career=e.target.value;state.page=1;request();});bind("tabla-search","input",function(e){state.search=e.target.value;if(state.timer)clearTimeout(state.timer);state.timer=setTimeout(function(){state.page=1;render();},250);});bind("tabla-refresh","click",function(){if(window.TablaCore&&TablaCore.clearCache)TablaCore.clearCache();state.periodKey="";state.depKey="";request();});bind("tabla-page-first","click",function(){state.page=1;request();});bind("tabla-page-prev","click",function(){state.page=Math.max(1,state.page-1);request();});bind("tabla-page-next","click",function(){state.page=Math.min(state.pagination?state.pagination.pages:state.page+1,state.page+1);request();});bind("tabla-page-last","click",function(){state.page=state.pagination?state.pagination.pages:state.page;request();});var chipsBox=el("tabla-req-chips");if(chipsBox)chipsBox.addEventListener("click",function(e){var b=e.target&&e.target.closest?e.target.closest("[data-req-filter]"):null;if(!b)return;var k=b.getAttribute("data-req-filter"),i=state.requirements.indexOf(k);if(k==="falta")state.requirements=i>=0?[]:["falta"];else{state.requirements=state.requirements.filter(function(x){return x!=="falta";});i=state.requirements.indexOf(k);if(i>=0)state.requirements.splice(i,1);else state.requirements.push(k);}state.page=1;request();});window.addEventListener("bdlocal:legacy-ready",render);window.addEventListener("bdlocal:legacy-snapshot",render);window.addEventListener("requisitos:bl:snapshot-changed",render);render();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
  window.TablaApp={render:render,getState:function(){return Object.assign({},state);}};
})(window,document);
