/* Exportación Word compatible por sección y global. */
(function(window){
  "use strict";
  var U=window.InPVCUtils;
  function styles(){return '<style>@page{size:A4;margin:2.3cm 2.2cm 2.3cm 2.5cm;}body{font-family:Arial,sans-serif;font-size:11pt;line-height:1.5;color:#172033;}h1{text-align:center;font-size:18pt;text-transform:uppercase}h2{font-size:15pt;color:#0f4c5c;border-bottom:2px solid #2f7d8c;padding-bottom:6px}h3{font-size:12pt;color:#183f4b;margin-top:18px}h4{font-size:11pt;margin-bottom:4px}p{text-align:justify}table{width:100%;border-collapse:collapse;margin:10px 0 16px;font-size:9pt}th,td{border:1px solid #a8b7bd;padding:5px;vertical-align:top}th{background:#dceff2;color:#173b45}.cover{height:22cm;display:flex;flex-direction:column;justify-content:center;text-align:center;page-break-after:always}.cover .unit{color:#2f7d8c;font-weight:bold;text-transform:uppercase}.cover .meta{margin-top:35px}.section{page-break-before:always}.inpvc-kpis{display:table;width:100%;margin:12px 0}.inpvc-kpis article{display:table-cell;border:1px solid #9eb8bf;padding:8px;text-align:center}.inpvc-kpis span,.inpvc-kpis strong{display:block}.inpvc-bars{margin:8px 0 18px}.inpvc-bar-row{display:table;width:100%;margin:5px 0}.inpvc-bar-row>span,.inpvc-bar-row>div,.inpvc-bar-row>strong{display:table-cell}.inpvc-bar-row>span{width:36%}.inpvc-bar-row>div{width:50%;background:#e7eef0}.inpvc-bar-row i{display:block;height:12px;background:#2f7d8c}.inpvc-bar-row>strong{width:14%;padding-left:8px}.inpvc-chart figcaption,.inpvc-caption{font-weight:bold}.inpvc-fish-branch{border-left:5px solid #2f7d8c;background:#eef6f7;padding:7px;margin:5px}.inpvc-fish-branch strong{display:block}.inpvc-fish-arrow{border:2px solid #2f7d8c;padding:10px;text-align:center;margin:12px 0}</style>';}
  function cover(ctx,title){var m=ctx.metadata;return '<section class="cover"><p class="unit">Unidad de Titulación y Eficiencia Terminal</p><h1>'+U.esc(title||"Informe final del proceso de titulación PVC")+'</h1><h2>'+U.esc(m.periodoLabel||m.periodoId)+'</h2><div class="meta"><p><strong>Código:</strong> '+U.esc(m.codigoInforme||"—")+'</p><p><strong>Fecha de elaboración:</strong> '+U.esc(m.fechaElaboracion||"—")+'</p><p><strong>Modalidad:</strong> Artículo Académico PVC</p></div></section>';}
  function build(ctx,sections,title){sections=Array.isArray(sections)?sections:[];return '<!doctype html><html><head><meta charset="utf-8">'+styles()+'</head><body>'+cover(ctx,title)+sections.map(function(section){return '<section class="section">'+section.html+'</section>';}).join("")+'</body></html>';}
  function filename(ctx,suffix){return U.slug('Informe_PVC_'+(ctx.metadata.periodoLabel||ctx.metadata.periodoId)+'_'+suffix)+'.doc';}
  function blob(ctx,sections,title){return new Blob(['\ufeff',build(ctx,sections,title)],{type:'application/msword;charset=utf-8'});}
  function downloadSection(ctx,section){U.download(blob(ctx,[section],section.title),filename(ctx,section.folder));}
  function downloadGlobal(ctx,sections){sections=sections&&sections.length?sections:ctx.sections;U.download(blob(ctx,sections,"Informe final del proceso de titulación PVC"),filename(ctx,"Completo"));}
  window.InPVCWord={build:build,blob:blob,filename:filename,downloadSection:downloadSection,downloadGlobal:downloadGlobal};
})(window);
