/* =========================================================
Nombre completo: bl-borrar-periodo.service.js
Ruta o ubicación: /Requisitos/BaseLocal/services/bl-borrar-periodo.service.js
Función o funciones:
- Validar y ejecutar el borrado seguro de un período en Base Local.
- Exigir respaldo Excel antes de modificar datos.
- Pedir doble confirmación cuando el período está vigente, es reciente o no se puede fechar.
- Archivar la información completa del período en historial durante 1 mes.
- Registrar un marcador en Firebase para que el período no reaparezca, sin borrado definitivo inmediato.
Con qué se conecta:
- baselocal.core.js
- bl-respaldo-periodo-excel.service.js
- firebase-config.js
========================================================= */
(function(window){
  "use strict";
  var CONFIRM_TEXT="BORRAR PERIODO";
  var ARCHIVED_COLLECTION="periodosArchivados";
  var ARCHIVE_DAYS=30;
  var MONTHS={enero:0,febrero:1,marzo:2,abril:3,mayo:4,junio:5,julio:6,agosto:7,septiembre:8,setiembre:8,octubre:9,noviembre:10,diciembre:11};
  function text(value){return String(value==null?"":value).trim();}
  function now(){return new Date().toISOString();}
  function clone(value){try{return JSON.parse(JSON.stringify(value==null?null:value));}catch(error){return value;}}
  function normalize(value){return text(value).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim().toLowerCase();}
  function safeId(value){return text(value||"periodo").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-zA-Z0-9_.-]+/g,"_").replace(/_+/g,"_").replace(/^_+|_+$/g,"")||"periodo";}
  function addDays(date,days){var d=new Date(date.getTime());d.setDate(d.getDate()+days);return d;}
  function endOfMonth(year,monthIndex){return new Date(year,monthIndex+1,0,23,59,59,999);}
  function addMonths(date,months){var d=new Date(date.getTime());d.setMonth(d.getMonth()+months);return d;}
  function samePeriod(a,b){if(!text(a)||!text(b)){return false;}try{if(window.BLPeriodosCanon&&typeof window.BLPeriodosCanon.samePeriod==="function"){return window.BLPeriodosCanon.samePeriod(a,b);}}catch(error){}return normalize(a)===normalize(b);}
  function periodIdOf(period){period=period||{};return text(period.id||period.periodoId||period.value||period.label||period.periodoLabel||period.periodo);}
  function periodLabelOf(period){period=period||{};return text(period.label||period.periodoLabel||period.periodo||period.id||period.periodoId);}
  function studentPeriodOf(student){student=student||{};return text(student.periodoId||student.periodo||student.Periodo||student.periodoLabel||student.ultimoPeriodoId);}
  function readSnapshot(){if(window.BaseLocalAPI&&typeof window.BaseLocalAPI.getSnapshot==="function"){return clone(window.BaseLocalAPI.getSnapshot())||{};}if(window.ExcelLocalStorage&&typeof window.ExcelLocalStorage.readSnapshot==="function"){return clone(window.ExcelLocalStorage.readSnapshot())||{};}throw new Error("No se pudo leer la Base Local.");}
  function writeSnapshot(snapshot){if(window.BaseLocalAPI&&typeof window.BaseLocalAPI.writeSnapshot==="function"){return window.BaseLocalAPI.writeSnapshot(snapshot,{source:"borrarPeriodo"});}if(window.ExcelLocalStorage&&typeof window.ExcelLocalStorage.writeSnapshot==="function"){return window.ExcelLocalStorage.writeSnapshot(snapshot);}throw new Error("No se pudo guardar la Base Local.");}
  function parsePeriodDateFromFields(period){period=period||{};var finAnio=Number(period.finAnio||period.anioFin||period.yearEnd||0);var finMesRaw=text(period.finMes||period.mesFin||period.monthEnd||"");var finMes=Number(finMesRaw);if(!finMes&&MONTHS[normalize(finMesRaw)]!==undefined){finMes=MONTHS[normalize(finMesRaw)]+1;}return finAnio>=2000&&finMes>=1&&finMes<=12?endOfMonth(finAnio,finMes-1):null;}
  function parsePeriodDateFromText(value){var clean=normalize(value);if(!clean){return null;}var machine=clean.match(/(20\d{2})[-_](\d{1,2})(?:_{1,2}|[-_a-z ]+)(20\d{2})[-_](\d{1,2})/);if(machine){return endOfMonth(Number(machine[3]),Number(machine[4])-1);}var matches=[];clean.replace(/(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|setiembre|octubre|noviembre|diciembre)\s+(?:de\s+)?(20\d{2})/g,function(_,mes,anio){matches.push({month:MONTHS[mes],year:Number(anio)});return _;});if(matches.length){var last=matches[matches.length-1];return endOfMonth(last.year,last.month);}var numeric=[];clean.replace(/(20\d{2})[-\/](\d{1,2})/g,function(_,anio,mes){numeric.push({month:Number(mes)-1,year:Number(anio)});return _;});if(numeric.length){var n=numeric[numeric.length-1];if(n.month>=0&&n.month<=11){return endOfMonth(n.year,n.month);}}return null;}
  function periodEndDate(period){return parsePeriodDateFromFields(period)||parsePeriodDateFromText(periodLabelOf(period))||parsePeriodDateFromText(periodIdOf(period));}
  function riskInfo(period){var end=periodEndDate(period);var today=new Date();if(!end){return {risk:"indeterminado",requiresDoubleConfirm:true,endDate:"",message:"No se pudo determinar la fecha final del período. Por seguridad se exige doble confirmación."};}var fiveMonths=addMonths(end,5);if(today<=end){return {risk:"vigente",requiresDoubleConfirm:true,endDate:end.toISOString(),message:"ALERTA: este período parece estar vigente. Verifica muy bien antes de borrar."};}if(today<=fiveMonths){return {risk:"reciente",requiresDoubleConfirm:true,endDate:end.toISOString(),message:"ALERTA: este período terminó hace menos de 5 meses. Se exige doble confirmación."};}return {risk:"antiguo",requiresDoubleConfirm:false,endDate:end.toISOString(),message:"El período parece antiguo. Igual se hará respaldo Excel antes de borrar."};}
  function relatedHistory(history,periodId){return (Array.isArray(history)?history:[]).filter(function(row){return samePeriod(row&&(row.periodoId||row.periodoLabel),periodId);});}
  function findPeriod(snapshot,periodId){return (Array.isArray(snapshot.periods)?snapshot.periods:[]).find(function(period){return samePeriod(periodIdOf(period),periodId)||samePeriod(periodLabelOf(period),periodId);})||null;}
  function periodStudents(snapshot,periodId){return (Array.isArray(snapshot.students)?snapshot.students:[]).filter(function(student){return samePeriod(studentPeriodOf(student),periodId)||samePeriod(student.periodoLabel,periodId);});}
  function isDeleteHistory(row){return text(row&&row.action)==="borrarPeriodo";}
  function isExpiredDeleteHistory(row){var limit=Date.parse(text(row&&(row.archivadoHasta||row.expiresAt)));return Number.isFinite(limit)&&Date.now()>limit;}
  function purgeExpired(history){return (Array.isArray(history)?history:[]).filter(function(row){return !isDeleteHistory(row)||!isExpiredDeleteHistory(row);});}
  function preview(periodId){periodId=text(periodId);if(!periodId){throw new Error("Selecciona un período antes de borrar.");}var snapshot=readSnapshot();var period=findPeriod(snapshot,periodId)||{id:periodId,label:periodId};var students=periodStudents(snapshot,periodId);var history=relatedHistory(snapshot.history,periodId);return Object.assign({ok:true,periodoId:periodId,periodoLabel:periodLabelOf(period)||periodId,period:period,totalStudents:students.length,totalHistory:history.length,confirmText:CONFIRM_TEXT},riskInfo(period));}
  function getFirebaseConfigIfAvailable(){try{if(typeof firebaseConfig!=="undefined"&&firebaseConfig){return firebaseConfig;}}catch(error){}return null;}
  function ensureFirebase(){if(!window.firebase||typeof window.firebase.firestore!=="function"){throw new Error("Firebase no está cargado.");}try{if(!window.firebase.apps.length){var cfg=getFirebaseConfigIfAvailable();if(!cfg){throw new Error("No existe configuración Firebase.");}window.firebase.initializeApp(cfg);}}catch(error){if(!window.firebase.apps||!window.firebase.apps.length){throw error;}}if(window.db&&typeof window.db.collection==="function"){return window.db;}try{if(typeof db!=="undefined"&&db&&typeof db.collection==="function"){return db;}}catch(error){}return window.firebase.firestore();}
  async function archiveRemotePeriod(plan, event){if(navigator.onLine===false){return {ok:false,skipped:true,reason:"Sin internet"};}try{var db=ensureFirebase();var payload={periodoId:plan.periodoId,periodoLabel:plan.periodoLabel,action:"borrarPeriodo",estado:"ARCHIVADO",archivadoEn:event.createdAt,archivadoHasta:event.archivadoHasta,backupFileName:event.backupFileName,totalStudents:event.totalStudents,riesgo:event.riesgo,source:"BaseLocal",updatedAt:now()};await db.collection(ARCHIVED_COLLECTION).doc(safeId(plan.periodoId)).set(payload,{merge:true});return {ok:true,skipped:false,collection:ARCHIVED_COLLECTION,docId:safeId(plan.periodoId)};}catch(error){return {ok:false,skipped:false,reason:error.message||String(error)};}}
  function notify(kind,payload){payload=payload||{};try{window.dispatchEvent(new CustomEvent("requisitos:bl:"+kind,{detail:payload}));window.dispatchEvent(new CustomEvent("baselocal:"+kind,{detail:payload}));}catch(error){}try{if(window.parent&&window.parent!==window){window.parent.postMessage({type:"requisitos:bl:"+kind,payload:payload},"*");}}catch(error){}try{window.localStorage.setItem("REQ_BL_SIGNAL_V1",JSON.stringify({id:"delete-period-"+Date.now(),kind:kind,payload:payload,at:now()}));}catch(error){}}
  function buildArchive(originalSnapshot,periodId,period,students,history){originalSnapshot=originalSnapshot||{};return {meta:clone(originalSnapshot.meta||{}),period:clone(period),periods:(Array.isArray(originalSnapshot.periods)?originalSnapshot.periods:[]).filter(function(p){return samePeriod(periodIdOf(p),periodId)||samePeriod(periodLabelOf(p),periodId);}),students:clone(students||[]),history:clone(history||[]),diagnostics:clone(originalSnapshot.diagnostics||[])};}
  async function borrar(options){options=options||{};var periodId=text(options.periodId||"");var plan=preview(periodId);if(plan.requiresDoubleConfirm&&text(options.confirmText)!==CONFIRM_TEXT){throw new Error("Para borrar este período debes escribir exactamente: "+CONFIRM_TEXT);}if(!window.BLRespaldoPeriodoExcelService||typeof window.BLRespaldoPeriodoExcelService.exportar!=="function"){throw new Error("No está cargado el servicio de respaldo Excel.");}var snapshot=readSnapshot();var originalSnapshot=clone(snapshot)||{};var period=findPeriod(originalSnapshot,periodId)||plan.period;var students=periodStudents(originalSnapshot,periodId);var history=relatedHistory(originalSnapshot.history,periodId);var backup=await window.BLRespaldoPeriodoExcelService.exportar({periodId:periodId,periodLabel:plan.periodoLabel,snapshot:originalSnapshot});if(!backup||!backup.ok){throw new Error("No se generó el respaldo Excel. No se borra el período.");}snapshot.periods=(Array.isArray(snapshot.periods)?snapshot.periods:[]).filter(function(p){return !(samePeriod(periodIdOf(p),periodId)||samePeriod(periodLabelOf(p),periodId));});snapshot.students=(Array.isArray(snapshot.students)?snapshot.students:[]).filter(function(student){return !(samePeriod(studentPeriodOf(student),periodId)||samePeriod(student.periodoLabel,periodId));});snapshot.history=purgeExpired(snapshot.history);var event={id:"borrar_periodo_"+Date.now(),action:"borrarPeriodo",periodoId:periodId,periodoLabel:plan.periodoLabel,fileName:backup.fileName,totalRows:students.length,totalStudents:students.length,totalPeriods:1,riesgo:plan.risk,mensajeRiesgo:plan.message,backupOk:true,backupFileName:backup.fileName,respaldoGeneradoEn:now(),archivadoHasta:addDays(new Date(),ARCHIVE_DAYS).toISOString(),createdAt:now(),respaldo:buildArchive(originalSnapshot,periodId,period,students,history)};snapshot.history.unshift(event);snapshot.meta=Object.assign({},snapshot.meta||{},{updatedAt:now(),lastDeletedPeriodId:periodId,lastDeletedPeriodLabel:plan.periodoLabel});var saved=writeSnapshot(snapshot);var firebaseArchive=await archiveRemotePeriod(plan,event);try{var after=readSnapshot();if(Array.isArray(after.history)&&after.history.length&&after.history[0].id===event.id){after.history[0].firebaseArchive=firebaseArchive;saved=writeSnapshot(after);}}catch(error){}notify("periodo-borrado",{periodoId:periodId,periodoLabel:plan.periodoLabel,totalStudents:students.length,backupFileName:backup.fileName,firebaseArchive:firebaseArchive});return {ok:true,periodoId:periodId,periodoLabel:plan.periodoLabel,totalStudents:students.length,backupFileName:backup.fileName,firebaseArchive:firebaseArchive,snapshot:saved};}
  function purgarHistorialVencido(options){options=options||{};var snapshot=readSnapshot();var before=Array.isArray(snapshot.history)?snapshot.history.length:0;snapshot.history=purgeExpired(snapshot.history);var removed=before-snapshot.history.length;if(removed&&options.save){writeSnapshot(snapshot);notify("periodo-borrado-historial-purgado",{removed:removed});}return {ok:true,removed:removed};}
  function deletedPeriodEntries(snapshot){var rows=Array.isArray(snapshot&&snapshot.history)?snapshot.history:[];return rows.filter(function(row){return isDeleteHistory(row)&&!isExpiredDeleteHistory(row);});}
  function isPeriodDeleted(periodId,snapshot){return deletedPeriodEntries(snapshot).some(function(row){return samePeriod(row.periodoId||row.periodoLabel,periodId);});}
  window.BLBorrarPeriodoService={preview:preview,borrar:borrar,purgarHistorialVencido:purgarHistorialVencido,deletedPeriodEntries:deletedPeriodEntries,isPeriodDeleted:isPeriodDeleted,confirmText:CONFIRM_TEXT};
})(window);
