/* Orquestador de pantalla y descargas InPVC. */
(function(window,document){
  "use strict";var U=window.InPVCUtils;var state={periods:[],context:null};
  function el(id){return document.getElementById(id);}function con(){return window.ConInPVC||window.BDLocalConeInPVC;}
  function status(message,type){var box=el("inpvc-status");if(box){box.className="inpvc-status "+(type||"");box.textContent=message;}}
  function periodId(row){return U.text(row&& (row.id||row.periodoId||row.value));}function periodLabel(row){return U.text(row&&(row.label||row.periodoLabel||row.nombre)||periodId(row));}
  function selectedPeriod(){var id=el("inpvc-period").value;return state.periods.find(function(p){return periodId(p)===id;})||null;}
  function updateCode(){var code=U.reportCode(el("inpvc-date").value);el("inpvc-code").value=code;return code;}
  function metadata(period){period=period||{};var date=U.text(el("inpvc-date").value);return {periodoId:periodId(period),periodoLabel:periodLabel(period),codigoInforme:U.reportCode(date),fechaElaboracion:date};}
  function selectedSections(){if(!state.context){return [];}var selected={};Array.prototype.forEach.call(document.querySelectorAll("[data-section-check]"),function(check){selected[check.value]=check.checked;});return state.context.sections.filter(function(section){return selected[section.id]!==false;});}
  function setEnabled(value){["inpvc-word-global","inpvc-pdf-global","inpvc-zip-global"].forEach(function(id){el(id).disabled=!value;});}
  function renderSummary(ctx){var s=ctx.summary;el("inpvc-total").textContent=s.total;el("inpvc-approved").textContent=s.aprobados;el("inpvc-failed").textContent=s.reprobados;el("inpvc-rate").textContent=s.porcentajeAprobacion+" %";}
  function renderSections(ctx){var host=el("inpvc-sections");host.innerHTML=ctx.sections.map(function(section){return '<article class="inpvc-section-card"><div class="inpvc-section-head"><label><input type="checkbox" data-section-check value="'+U.esc(section.id)+'" checked><span>'+section.order+'</span><div><h3>'+U.esc(section.title)+'</h3><p>'+U.esc(section.folder)+'</p></div></label><div class="inpvc-section-actions"><button type="button" data-word="'+U.esc(section.id)+'">Word</button><button type="button" data-pdf="'+U.esc(section.id)+'">PDF</button></div></div><details><summary>Vista previa</summary><div class="inpvc-document-preview">'+section.html+'</div></details></article>';}).join("");}
  function generate(){var period=selectedPeriod();if(!period){status("Selecciona un período PVC.","warn");return;}status("Leyendo estudiantes y notas desde Base Local...","");setEnabled(false);con().listStudents({periodoId:periodId(period)}).then(function(rows){state.context=window.InPVCModel.create(metadata(period),rows);renderSummary(state.context);renderSections(state.context);setEnabled(state.context.ok);status(state.context.ok?"Informe PVC listo: "+rows.length+" estudiantes y "+state.context.sections.length+" secciones.":"El período no contiene estudiantes para generar el informe.",state.context.ok?"ok":"warn");}).catch(function(error){status(error.message||String(error),"bad");});}
  function fillPeriods(){return con().listPeriods().then(function(rows){state.periods=rows||[];el("inpvc-period").innerHTML='<option value="">Selecciona un período PVC</option>'+state.periods.map(function(p){return '<option value="'+U.esc(periodId(p))+'">'+U.esc(periodLabel(p))+'</option>';}).join("");status(state.periods.length?"Selecciona el período PVC para preparar el informe.":"No se encontraron períodos PVC en Base Local.",state.periods.length?"":"warn");});}
  function onPeriod(){var p=selectedPeriod()||{};var savedDate=U.text(p.fechaElaboracion||p.fechaInforme||p.fecha);el("inpvc-date").value=/^\d{4}-\d{2}-\d{2}$/.test(savedDate)?savedDate:new Date().toISOString().slice(0,10);updateCode();state.context=null;el("inpvc-sections").innerHTML='<div class="inpvc-empty">Presiona “Generar informe” para construir las secciones.</div>';setEnabled(false);}
  function findSection(id){return state.context&&state.context.sections.find(function(section){return section.id===id;});}
  function bind(){el("inpvc-period").addEventListener("change",onPeriod);el("inpvc-date").addEventListener("input",updateCode);el("inpvc-date").addEventListener("change",updateCode);el("inpvc-generate").addEventListener("click",generate);el("inpvc-refresh").addEventListener("click",function(){status("Actualizando Base Local...","");con().refresh({periodoId:el("inpvc-period").value,force:true}).then(fillPeriods).catch(function(e){status(e.message,"bad");});});el("inpvc-sections").addEventListener("click",function(event){var word=event.target.getAttribute("data-word"),pdf=event.target.getAttribute("data-pdf"),section=findSection(word||pdf);if(!section){return;}if(word){try{window.InPVCWord.downloadSection(state.context,section);}catch(error){status(error.message,"bad");}return;}status("Generando PDF de "+section.title+"...","");window.InPVCPdf.downloadSection(state.context,section).then(function(){status("PDF de "+section.title+" generado correctamente.","ok");}).catch(function(error){status(error.message,"bad");});});el("inpvc-word-global").addEventListener("click",function(){window.InPVCWord.downloadGlobal(state.context,selectedSections());});el("inpvc-pdf-global").addEventListener("click",function(){status("Generando PDF global...","");window.InPVCPdf.downloadGlobal(state.context,selectedSections()).then(function(){status("PDF global generado correctamente.","ok");}).catch(function(error){status(error.message,"bad");});});el("inpvc-zip-global").addEventListener("click",function(){status("Preparando ZIP con subcarpetas...","");window.InPVCZip.download(state.context,selectedSections()).then(function(){status("ZIP completo generado correctamente.","ok");}).catch(function(error){status(error.message,"bad");});});el("inpvc-select-all").addEventListener("click",function(){Array.prototype.forEach.call(document.querySelectorAll("[data-section-check]"),function(c){c.checked=true;});});el("inpvc-select-none").addEventListener("click",function(){Array.prototype.forEach.call(document.querySelectorAll("[data-section-check]"),function(c){c.checked=false;});});}
  function init(){el("inpvc-date").value=new Date().toISOString().slice(0,10);updateCode();bind();fillPeriods().catch(function(error){status(error.message||String(error),"bad");});}
  window.InPVCApp={init:init,generate:generate,state:state};init();
})(window,document);
