(function(window){
  "use strict";
  var CACHE_KEY="REQ_BDLOCAL_CONEXIONES_CACHE_V1";
  var SIGNAL_KEY="REQ_BDLOCAL_CONEXIONES_SIGNAL_V1";
  function text(v){return String(v==null?"":v).trim();}
  function nowISO(){return new Date().toISOString();}
  function clone(v){try{return JSON.parse(JSON.stringify(v));}catch(e){return v;}}
  function safeParse(v,f){try{return v?JSON.parse(v):f;}catch(e){return f;}}
  function normalizeBasic(v){return text(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ").trim();}
  function normalizeKey(v){return normalizeBasic(v).toLowerCase().replace(/[^a-z0-9]+/g,"");}
  function normalizeCedula(v){var r=text(v).replace(/[^0-9A-Za-z]/g,"");return /^\d{9}$/.test(r)?"0"+r:r;}
  function canonicalPeriodId(v){v=text(v);var m=v.match(/^(\d{4})-(\d{2})_+(\d{4})-(\d{2})$/);return m?m[1]+"-"+m[2]+"__"+m[3]+"-"+m[4]:v.replace(/_+/g,"__");}
  function normalizePeriod(p){p=p||{};var id=canonicalPeriodId(p.periodoCanonicoId||p.periodoId||p.id||p.value||p.key||"");if(!id){return null;}var label=text(p.periodoCanonicoLabel||p.periodoLabel||p.label||p.nombre||p.name||id);return Object.assign({},p,{id:id,value:id,key:id,label:label,nombre:label,periodoId:id,periodoLabel:label,periodoCanonicoId:id,periodoCanonicoLabel:label});}
  function samePeriod(a,b){a=canonicalPeriodId(a);b=canonicalPeriodId(b);return !b||!!a&&(a===b||normalizeKey(a)===normalizeKey(b));}
  function emptyCache(){return {meta:{app:"Requisitos",module:"BDLocalConexiones",version:"1.0.0",source:"empty",updatedAt:nowISO(),totalPeriods:0,totalStudents:0},periods:[],students:[],requirements:[],summaries:{},diagnostics:[]};}
  function normalizeStudent(row){row=Object.assign({},row||{});var ced=normalizeCedula(row.cedula||row.numeroIdentificacion||row.NumeroIdentificacion||row.identificacion||row.Identificacion||row.Cedula||row["Cédula"]||"");var pid=canonicalPeriodId(row.periodoId||row.periodId||row.ultimoPeriodoId||row.idPeriodo||row._periodoId||row._bl2PeriodoId||"");var pl=text(row.periodoLabel||row.periodo||row.Periodo||row._periodo||row._bl2Periodo||pid);row.id=row.id||row._id||(ced&&pid?ced+"__"+pid:ced);row._id=row._id||row.id;row.cedula=ced;row._cedula=row._cedula||ced;row.numeroIdentificacion=row.numeroIdentificacion||ced;row.NumeroIdentificacion=row.NumeroIdentificacion||ced;row.periodoId=pid;row.periodId=pid;row.ultimoPeriodoId=row.ultimoPeriodoId||pid;row.periodoLabel=pl;row.Periodo=row.Periodo||pl;row._periodoId=row._periodoId||pid;row._periodo=row._periodo||pl;row._nombres=row._nombres||row.Nombres||row.nombres||row.Nombre||row.nombre||row.Estudiante||row.estudiante||"";row._carrera=row._carrera||row.NombreCarrera||row.nombreCarrera||row.Carrera||row.carrera||"";row._division=row._division||row.division||row.Division||row["División"]||"Sin división";row._estadoMatricula=text(row._estadoMatricula||row.estadoMatricula||row.EstadoMatricula||"ACTIVO").toUpperCase()==="RETIRADO"?"RETIRADO":"ACTIVO";return row;}
  function normalizeCache(c){c=c&&typeof c==="object"?c:emptyCache();c.meta=c.meta&&typeof c.meta==="object"?c.meta:{};c.periods=Array.isArray(c.periods)?c.periods.map(normalizePeriod).filter(Boolean):[];c.students=Array.isArray(c.students)?c.students.map(normalizeStudent):[];c.requirements=Array.isArray(c.requirements)?c.requirements:[];c.summaries=c.summaries&&typeof c.summaries==="object"?c.summaries:{};c.diagnostics=Array.isArray(c.diagnostics)?c.diagnostics:[];c.meta.app=c.meta.app||"Requisitos";c.meta.module=c.meta.module||"BDLocalConexiones";c.meta.version=c.meta.version||"1.0.0";c.meta.source=c.meta.source||"cache";c.meta.updatedAt=c.meta.updatedAt||nowISO();c.meta.totalPeriods=c.periods.length;c.meta.totalStudents=c.students.length;return c;}
  function readCache(){return normalizeCache(safeParse(localStorage.getItem(CACHE_KEY),null));}
  function writeCache(c){c=normalizeCache(c);c.meta.updatedAt=nowISO();try{localStorage.setItem(CACHE_KEY,JSON.stringify(c));}catch(e){}emit("bdlocal:conexiones-cache-updated",{periods:c.periods.length,students:c.students.length,source:c.meta.source||"BDLocal"});return clone(c);}
  function emit(name,detail){detail=Object.assign({at:nowISO()},clone(detail||{}));try{window.dispatchEvent(new CustomEvent(name,{detail:detail}));}catch(e){}try{localStorage.setItem(SIGNAL_KEY,JSON.stringify({name:name,detail:detail}));}catch(e2){}}
  function filterStudents(rows,opt){opt=opt||{};rows=Array.isArray(rows)?rows.map(normalizeStudent):[];var pid=canonicalPeriodId(opt.periodoId||opt.periodId||opt.period||"");var mat=text(opt.estadoMatricula||opt.matricula||"");var div=normalizeBasic(opt.division||"").toLowerCase();var q=normalizeBasic(opt.search||opt.busqueda||opt.query||"").toLowerCase();return rows.filter(function(r){if(pid&&!samePeriod(r.periodoId||r._periodoId||r.ultimoPeriodoId,pid)){return false;}if(mat&&text(r._estadoMatricula||r.estadoMatricula).toUpperCase()!==mat.toUpperCase()){return false;}if(div&&normalizeBasic(r._division||r.division||"").toLowerCase()!==div){return false;}if(q){var h=normalizeBasic([r.cedula,r.numeroIdentificacion,r.Nombres,r.nombres,r._nombres,r.NombreCarrera,r.CodigoCarrera,r._carrera,r._division,r.CorreoPersonal,r.CorreoInstitucional,r.Celular].join(" ")).toLowerCase();return h.indexOf(q)>=0;}return true;});}
  function getGlobal(name){return window[name]||null;}
  window.BDLocalConUtils={version:"1.0.0",cacheKey:CACHE_KEY,signalKey:SIGNAL_KEY,text:text,nowISO:nowISO,clone:clone,safeParse:safeParse,normalizeBasic:normalizeBasic,normalizeKey:normalizeKey,normalizeCedula:normalizeCedula,canonicalPeriodId:canonicalPeriodId,normalizePeriod:normalizePeriod,samePeriod:samePeriod,normalizeStudent:normalizeStudent,filterStudents:filterStudents,emptyCache:emptyCache,normalizeCache:normalizeCache,readCache:readCache,writeCache:writeCache,emit:emit,getGlobal:getGlobal};
})(window);
