(function(window,document){
  "use strict";
  function $(s){return document.querySelector(s);}function txt(v){return String(v==null?"":v).trim();}function esc(v){return txt(v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c];});}function js(v){try{return JSON.stringify(v,null,2);}catch(e){return String(v);}}function out(v){var e=$("#blOutput");if(e)e.textContent=typeof v==="string"?v:js(v);}function norm(v){return txt(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}
  var stores=[], lastFirebase=0, lastDiff=0;
  function initStores(){var s=window.BDLConfig&&window.BDLConfig.stores?window.BDLConfig.stores:{};stores=Object.keys(s).map(function(k){return s[k];});}
  function idOf(r){r=r||{};return txt(r.clave||r.id||r.idRegistro||r.idEstudiantePeriodo||r.numeroIdentificacion||r.NumeroIdentificacion||r.cedula||r.Cedula||r.periodoId||r.requisitoKey||r.carreraKey||r.codigoCarrera||r._docId||"");}
  function cedulaOf(r){r=r||{};return txt(r.numeroIdentificacion||r.NumeroIdentificacion||r.cedula||r.Cedula||r.CEDULA||r.identificacion||r.Identificacion||r._docId||r.id).replace(/[^0-9A-Za-z]/g,"");}
  function periodOf(r,fallback){r=r||{};var raw=txt(r.periodoId||r.PeriodoId||r.periodo||r.Periodo||r.periodoLabel||r.PeriodoLabel||r.label||r.id||r._docId||fallback||"");if(window.BDLNormPeriodo){return window.BDLNormPeriodo.normalize({},raw).periodoId;}return raw.replace(/\s+/g,"_");}
  function canonicalId(row,period){return (cedulaOf(row)||"SIN_IDENTIFICACION")+"_"+(periodOf(row,period)||"SIN_PERIODO");}
  function localRows(store){return window.BDLDB?window.BDLDB.list(store,{limit:0}).catch(function(){return [];}):Promise.resolve([]);}
  function fireRows(col){if(!window.BDLSyncFirebase||!window.BDLSyncFirebase.listUpdated)return Promise.resolve([]);return window.BDLSyncFirebase.listUpdated(col,"",5000).catch(function(error){out({ok:false,error:error&&error.message?error.message:String(error)});return [];});}
  function fireSet(col,row,id){if(!window.BDLSyncFirebase||!window.BDLSyncFirebase.setDoc)return Promise.reject(new Error('Firebase no disponible'));var docId=id||idOf(row)||('auto_'+Date.now()+'_'+Math.random().toString(36).slice(2));var data=Object.assign({},row||{},{updatedAt:(row&&(row.updatedAt||row.actualizadoEn))||new Date().toISOString()});delete data._docId;delete data._collectionName;return window.BDLSyncFirebase.setDoc(col,docId,data);}
  function fill(){var t=$("#blTable");if(t){var extra=["Estudiantes","estudiantes","EstudiantesRequisitos","requisitos_estudiantes","Periodos"];var all=stores.concat(extra.filter(function(x){return stores.indexOf(x)<0;}));t.innerHTML=all.map(function(x){return '<option value="'+esc(x)+'">'+esc(x)+'</option>';}).join("");}if(window.BDLRepoPeriodos){window.BDLRepoPeriodos.listar().then(function(rows){var p=$("#blPeriod");if(!p)return;var current=p.value;p.innerHTML='<option value="">Todos los períodos</option>'+(rows||[]).map(function(r){return '<option value="'+esc(r.periodoId)+'">'+esc(r.periodoLabel||r.periodoId)+'</option>';}).join("");if(current)p.value=current;});}}
  function filterPeriod(rows){var p=$("#blPeriod")?$("#blPeriod").value:"";if(!p)return rows||[];return (rows||[]).filter(function(r){return periodOf(r,"")===p;});}
  function render(rows){rows=rows||[];var w=$("#blTableWrap");if(!w)return;if(!rows.length){w.innerHTML='<div class="bl-empty">No hay registros.</div>';return;}var keys=[];rows.slice(0,50).forEach(function(r){Object.keys(r||{}).forEach(function(k){if(keys.indexOf(k)<0)keys.push(k);});});keys=keys.slice(0,24);var h='<table class="bl-table"><thead><tr>'+keys.map(function(k){return '<th>'+esc(k)+'</th>';}).join('')+'<th>Ver</th></tr></thead><tbody>';h+=rows.slice(0,500).map(function(r,i){return '<tr>'+keys.map(function(k){var v=r[k];return '<td>'+esc(typeof v==="object"?js(v):v)+'</td>';}).join('')+'<td><button class="bl-btn light" data-row="'+i+'">JSON</button></td></tr>';}).join('');h+='</tbody></table>';w.innerHTML=h;Array.prototype.slice.call(w.querySelectorAll('[data-row]')).forEach(function(b){b.onclick=function(){openModal('Registro exacto',rows[Number(b.getAttribute('data-row'))]);};});}
  function loadTable(){var src=$("#blSource").value, table=$("#blTable").value;out('Cargando '+table+'...');return (src==="firebase"?fireRows(table):localRows(table)).then(function(rows){rows=filterPeriod(rows);if(src==="firebase")lastFirebase=rows.length;render(rows);counts();out({fuente:src,tabla:table,registros:rows.length});});}
  function allLocal(){var res={},p=Promise.resolve();stores.forEach(function(s){p=p.then(function(){return localRows(s).then(function(r){res[s]=r;});});});return p.then(function(){return res;});}
  function compare(){out('Comparando...');return Promise.all([allLocal(),fireRows($("#blTable").value)]).then(function(a){var table=$("#blTable").value, local=a[0][table]||[], remote=a[1]||[], lm={},rm={};local.forEach(function(r){var id=idOf(r);if(id)lm[id]=r;});remote.forEach(function(r){var id=idOf(r);if(id)rm[id]=r;});var d={tabla:table,local:local.length,firebase:remote.length,nuevosLocales:[],nuevosFirebase:[],diferentes:[]};Object.keys(lm).forEach(function(id){if(!rm[id])d.nuevosLocales.push(id);else if(js(lm[id])!==js(rm[id]))d.diferentes.push(id);});Object.keys(rm).forEach(function(id){if(!lm[id])d.nuevosFirebase.push(id);});lastDiff=d.nuevosLocales.length+d.nuevosFirebase.length+d.diferentes.length;lastFirebase=remote.length;counts();out(d);return d;});}
  function sync(){if(!window.BDLSync||!window.BDLSync.syncNow){out('BDLSync no disponible.');return;}out('Sincronizando diferencias...');return window.BDLSync.syncNow({manual:true,full:false}).then(function(r){out(r);counts();fill();return loadTable();}).catch(function(e){out({ok:false,error:e&&e.message?e.message:String(e)});});}
  function upload(){out('Subiendo todas las tablas locales a Firebase...');return allLocal().then(function(data){var r={subidos:0,errores:0,tablas:{}};var p=Promise.resolve();Object.keys(data).forEach(function(store){r.tablas[store]=data[store].length;(data[store]||[]).forEach(function(row){p=p.then(function(){return fireSet(store,row).then(function(){r.subidos++;}).catch(function(){r.errores++;});});});});return p.then(function(){out(r);counts();return r;});});}
  function download(){if(!window.BDLSyncDownload){out('BDLSyncDownload no disponible.');return;}out('Bajando Firebase a BDLocal...');return Promise.all([window.BDLSyncDownload.bajarPeriodos(''),window.BDLSyncDownload.bajarEstudiantes('')]).then(function(r){out({bajada:r});counts();fill();return loadTable();}).catch(function(e){out({ok:false,error:e&&e.message?e.message:String(e)});});}
  function purge(){var period=$("#blPeriod")?$("#blPeriod").value:"";var localPurge=window.BDLRepoPeriodos&&window.BDLRepoPeriodos.purgar?window.BDLRepoPeriodos.purgar():Promise.resolve({ok:true});if(!period){out('Purgando períodos locales. Seleccione un período para purgar también estudiantes.');return localPurge.then(function(r){fill();out(r);});}out('Purgando formatos de períodos y estudiantes...');return localPurge.then(function(periodResult){return fireRows('Estudiantes').then(function(rows){var res={periodos:periodResult,periodoUsado:period,revisados:rows.length,normalizados:0,errores:0};var p=Promise.resolve();rows.forEach(function(row){p=p.then(function(){var ced=cedulaOf(row);if(!ced){res.errores++;return null;}var data=Object.assign({},row,{numeroIdentificacion:ced,cedula:ced,Cedula:ced,periodoId:period,Periodo:period,periodo:period,formatoCanonico:true,formatoCanonicoId:canonicalId(row,period),updatedAt:new Date().toISOString()});return fireSet('Estudiantes',data,data.formatoCanonicoId).then(function(){res.normalizados++;}).catch(function(){res.errores++;});});});return p.then(function(){out(res);fill();return download();});});});}
  function search(){var q=norm($("#blSearch").value);var box=$("#blSearchResults");if(!q){box.innerHTML='<div class="bl-empty">Escriba un dato para buscar.</div>';return;}return allLocal().then(function(data){var found=[];Object.keys(data).forEach(function(store){(data[store]||[]).forEach(function(r){if(norm(js(r)).indexOf(q)>=0)found.push({store:store,row:r});});});found=found.slice(0,50);if(!found.length){box.innerHTML='<div class="bl-empty">No se encontró ningún dato.</div>';out({busqueda:q,resultados:0});return;}box.innerHTML=found.map(function(x,i){var n=txt(x.row.nombres||x.row.Nombres||x.row.nombre||x.row.numeroIdentificacion||x.row.cedula||x.row.Cedula||x.row.id||'Registro');return '<div class="bl-result"><div><strong>'+esc(n)+'</strong><br><small>BDLocal · '+esc(x.store)+'</small></div><button class="bl-btn light" data-found="'+i+'">Ver datos</button></div>';}).join('');Array.prototype.slice.call(box.querySelectorAll('[data-found]')).forEach(function(b){b.onclick=function(){var x=found[Number(b.getAttribute('data-found'))];openModal('Datos exactos · '+x.store,x.row);};});out({busqueda:q,resultados:found.length});});}
  function diag(){allLocal().then(function(d){var c={};Object.keys(d).forEach(function(k){c[k]=d[k].length;});out({fecha:new Date().toISOString(),bdlocal:c,firebase:!!window.BDLSyncFirebase});});}
  function counts(){allLocal().then(function(d){var total=Object.keys(d).reduce(function(a,k){return a+d[k].length;},0);if($("#blCountLocal"))$("#blCountLocal").textContent=total;if($("#blCountFirebase"))$("#blCountFirebase").textContent=lastFirebase;if($("#blCountDiff"))$("#blCountDiff").textContent=lastDiff;localRows('sync_queue').then(function(q){if($("#blCountQueue"))$("#blCountQueue").textContent=q.length;});});}
  function openModal(t,d){$("#blModalTitle").textContent=t;$("#blModalBody").textContent=js(d);$("#blModal").hidden=false;}function closeModal(){$("#blModal").hidden=true;}
  function bind(){$("#blBtnLoadTable").onclick=loadTable;$("#blBtnDiff").onclick=compare;$("#blBtnSync").onclick=sync;$("#blBtnUpload").onclick=upload;$("#blBtnDownload").onclick=download;$("#blBtnPurge").onclick=purge;$("#blBtnSearch").onclick=search;$("#blSearch").onkeydown=function(e){if(e.key==='Enter')search();};$("#blBtnDiag").onclick=diag;$("#blModalClose").onclick=closeModal;}
  function boot(){initStores();fill();bind();counts();out('BL listo.');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})(window,document);