(function(window,document){
  "use strict";

  function $(s){return document.querySelector(s);}
  function $all(s){return Array.prototype.slice.call(document.querySelectorAll(s));}
  function txt(v){return String(v==null?"":v).trim();}
  function esc(v){return txt(v).replace(/[&<>"']/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c];});}
  function js(v){try{return JSON.stringify(v,null,2);}catch(e){return String(v);}}
  function out(v){var e=$("#blOutput");if(e){e.textContent=typeof v==="string"?v:js(v);}}
  function norm(v){return txt(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();}
  function now(){return new Date().toISOString();}

  var stores=[], lastFirebase=0, lastDiff=0;
  var purgeState={source:"local",issues:[],lastReport:"",backupRows:[],summaryRows:[],running:false};

  function initStores(){var s=window.BDLConfig&&window.BDLConfig.stores?window.BDLConfig.stores:{};stores=Object.keys(s).map(function(k){return s[k];});}
  function idOf(r){r=r||{};return txt(r.clave||r.id||r.idRegistro||r.idEstudiantePeriodo||r.numeroIdentificacion||r.NumeroIdentificacion||r.cedula||r.Cedula||r.periodoId||r.requisitoKey||r.carreraKey||r.codigoCarrera||r._docId||"");}
  function cedulaOf(r){r=r||{};return txt(r.numeroIdentificacion||r.NumeroIdentificacion||r.cedula||r.Cedula||r.CEDULA||r.identificacion||r.Identificacion||r._docId||r.id).replace(/[^0-9A-Za-z]/g,"");}
  function celularOf(r){r=r||{};return txt(r.Celular||r.celular||r.telefono||r.Telefono||r.teléfono||r.TelefonoMovil||r.celularEstudiante||"").replace(/[^0-9]/g,"");}
  function nombreOf(r){r=r||{};return txt(r.nombres||r.Nombres||r.Nombre||r.nombre||r.ApellidosNombres||r.estudiante||r.Estudiante||r.numeroIdentificacion||r.Cedula||r._docId||"Registro");}
  function periodOf(r,fallback){r=r||{};var raw=txt(r.periodoId||r.PeriodoId||r.periodo||r.Periodo||r.periodoLabel||r.PeriodoLabel||r.label||r.id||r._docId||fallback||"");if(window.BDLNormPeriodo){return window.BDLNormPeriodo.normalize({},raw).periodoId;}return raw.replace(/\s+/g,"_");}
  function periodLabel(raw){if(window.BDLNormPeriodo){return window.BDLNormPeriodo.normalize({},raw).periodoLabel;}return txt(raw);}
  function canonicalId(row,period){return (cedulaOf(row)||"SIN_IDENTIFICACION")+"_"+(periodOf(row,period)||"SIN_PERIODO");}
  function completeness(row){var n=0;Object.keys(row||{}).forEach(function(k){var v=row[k];if(v!==null&&v!==undefined&&txt(typeof v==="object"?js(v):v)!==""){n++;}});return n;}
  function timeValue(v){if(!v){return 0;}if(v instanceof Date){return v.getTime();}if(typeof v==="object"&&typeof v.seconds==="number"){return v.seconds*1000;}var n=Date.parse(txt(v));return Number.isFinite(n)?n:0;}
  function rowTime(row){row=row||{};var keys=["updatedAt","actualizadoEn","actualizadaEn","ultimaSincronizacion","fechaActualizacion","modifiedAt","createdAt","creadoEn","fechaCreacion","_updateTime","_createTime"];return keys.reduce(function(max,k){return Math.max(max,timeValue(row[k]));},0);}
  function rowTimeText(row){var t=rowTime(row);return t?new Date(t).toISOString():"sin fecha";}
  function isEmptyValue(v){return v===null||v===undefined||txt(typeof v==="object"?js(v):v)==="";}
  function mergeSmart(primary,docs){var merged=Object.assign({},primary.data||{});var sources=[];docs.forEach(function(d){sources.push({id:d.id,fecha:d.updatedAtText,nombre:nombreOf(d.data),score:d.score});Object.keys(d.data||{}).forEach(function(k){if(k==="_docId"||k==="_collectionName"){return;}if(isEmptyValue(merged[k])&&!isEmptyValue(d.data[k])){merged[k]=d.data[k];}});});merged.updatedAt=now();merged.estadoDepuracion="REGISTRO_PRINCIPAL_CORREGIDO";merged.criterioConservacion="MAS_RECIENTE";merged.fusionInteligente=true;merged.fuentesFusion=sources;return merged;}

  function setProgress(current,total,label){var box=$("#blPurgeProgressBox"),bar=$("#blPurgeProgressBar"),textEl=$("#blPurgeProgressText"),pctEl=$("#blPurgeProgressPct");if(!box||!bar){return;}box.hidden=false;total=Math.max(1,Number(total||1));current=Math.max(0,Math.min(total,Number(current||0)));var pct=Math.round((current/total)*100);bar.style.width=pct+"%";if(textEl){textEl.textContent=label||"Procesando...";}if(pctEl){pctEl.textContent=pct+"%";}}
  function resetProgress(){setProgress(0,1,"Preparando...");var box=$("#blPurgeProgressBox");if(box){box.hidden=true;}}
  function lockPurge(value){purgeState.running=!!value;["#blPurgeAnalyze","#blPurgeSelectAll","#blPurgeClearAll","#blPurgeApply","#blPurgeDownloadExcel"].forEach(function(sel){var b=$(sel);if(b){b.disabled=value || b.disabled && value;}});}

  function localRows(store){return window.BDLDB?window.BDLDB.list(store,{limit:0}).catch(function(){return [];}):Promise.resolve([]);}
  function fireRows(col){if(!window.BDLSyncFirebase||!window.BDLSyncFirebase.listUpdated){return Promise.resolve([]);}return window.BDLSyncFirebase.listUpdated(col,"",5000).catch(function(error){out({ok:false,error:error&&error.message?error.message:String(error)});return [];});}
  function fireSet(col,row,id){if(!window.BDLSyncFirebase||!window.BDLSyncFirebase.setDoc){return Promise.reject(new Error("Firebase no disponible"));}var docId=id||idOf(row)||("auto_"+Date.now()+"_"+Math.random().toString(36).slice(2));var data=Object.assign({},row||{},{updatedAt:(row&&(row.updatedAt||row.actualizadoEn))||now()});delete data._docId;delete data._collectionName;return window.BDLSyncFirebase.setDoc(col,docId,data);}
  function putLocal(store,row){if(!window.BDLDB){return Promise.reject(new Error("BDLocal no disponible"));}return window.BDLDB.put(store,row);}

  function fill(){
    var t=$("#blTable");
    if(t){var extra=["Estudiantes","estudiantes","EstudiantesRequisitos","requisitos_estudiantes","Periodos"];var all=stores.concat(extra.filter(function(x){return stores.indexOf(x)<0;}));t.innerHTML=all.map(function(x){return '<option value="'+esc(x)+'">'+esc(x)+'</option>';}).join("");}
    if(window.BDLRepoPeriodos){window.BDLRepoPeriodos.listar().then(function(rows){var p=$("#blPeriod");if(!p)return;var current=p.value;p.innerHTML='<option value="">Todos los períodos</option>'+(rows||[]).map(function(r){return '<option value="'+esc(r.periodoId)+'">'+esc(r.periodoLabel||r.periodoId)+'</option>';}).join("");if(current){p.value=current;}});}
  }
  function filterPeriod(rows){var p=$("#blPeriod")?$("#blPeriod").value:"";if(!p)return rows||[];return (rows||[]).filter(function(r){return periodOf(r,"")===p;});}
  function render(rows){rows=rows||[];var w=$("#blTableWrap");if(!w)return;if(!rows.length){w.innerHTML='<div class="bl-empty">No hay registros.</div>';return;}var keys=[];rows.slice(0,50).forEach(function(r){Object.keys(r||{}).forEach(function(k){if(keys.indexOf(k)<0)keys.push(k);});});keys=keys.slice(0,24);var h='<table class="bl-table"><thead><tr>'+keys.map(function(k){return '<th>'+esc(k)+'</th>';}).join('')+'<th>Ver</th></tr></thead><tbody>';h+=rows.slice(0,500).map(function(r,i){return '<tr>'+keys.map(function(k){var v=r[k];return '<td>'+esc(typeof v==="object"?js(v):v)+'</td>';}).join('')+'<td><button class="bl-btn light" data-row="'+i+'">JSON</button></td></tr>';}).join('');h+='</tbody></table>';w.innerHTML=h;$all('[data-row]').forEach(function(b){b.onclick=function(){openModal('Registro exacto',rows[Number(b.getAttribute('data-row'))]);};});}
  function loadTable(){var src=$("#blSource").value, table=$("#blTable").value;out('Cargando '+table+'...');return (src==="firebase"?fireRows(table):localRows(table)).then(function(rows){rows=filterPeriod(rows);if(src==="firebase"){lastFirebase=rows.length;}render(rows);counts();out({fuente:src,tabla:table,registros:rows.length});});}
  function allLocal(){var res={},p=Promise.resolve();stores.forEach(function(s){p=p.then(function(){return localRows(s).then(function(r){res[s]=r;});});});return p.then(function(){return res;});}
  function compare(){out('Comparando...');return Promise.all([allLocal(),fireRows($("#blTable").value)]).then(function(a){var table=$("#blTable").value, local=a[0][table]||[], remote=a[1]||[], lm={},rm={};local.forEach(function(r){var id=idOf(r);if(id)lm[id]=r;});remote.forEach(function(r){var id=idOf(r);if(id)rm[id]=r;});var d={tabla:table,local:local.length,firebase:remote.length,nuevosLocales:[],nuevosFirebase:[],diferentes:[]};Object.keys(lm).forEach(function(id){if(!rm[id])d.nuevosLocales.push(id);else if(js(lm[id])!==js(rm[id]))d.diferentes.push(id);});Object.keys(rm).forEach(function(id){if(!lm[id])d.nuevosFirebase.push(id);});lastDiff=d.nuevosLocales.length+d.nuevosFirebase.length+d.diferentes.length;lastFirebase=remote.length;counts();out(d);return d;});}
  function sync(){if(!window.BDLSync||!window.BDLSync.syncNow){out('BDLSync no disponible.');return;}out('Sincronizando diferencias...');return window.BDLSync.syncNow({manual:true,full:false}).then(function(r){out(r);counts();fill();return loadTable();}).catch(function(e){out({ok:false,error:e&&e.message?e.message:String(e)});});}
  function upload(){out('Subiendo todas las tablas locales a Firebase...');return allLocal().then(function(data){var r={subidos:0,errores:0,tablas:{}};var p=Promise.resolve();Object.keys(data).forEach(function(store){r.tablas[store]=data[store].length;(data[store]||[]).forEach(function(row){p=p.then(function(){return fireSet(store,row).then(function(){r.subidos++;}).catch(function(){r.errores++;});});});});return p.then(function(){out(r);counts();return r;});});}
  function download(){if(!window.BDLSyncDownload){out('BDLSyncDownload no disponible.');return;}out('Bajando Firebase a BDLocal...');return Promise.all([window.BDLSyncDownload.bajarPeriodos(''),window.BDLSyncDownload.bajarEstudiantes('')]).then(function(r){out({bajada:r});counts();fill();return loadTable();}).catch(function(e){out({ok:false,error:e&&e.message?e.message:String(e)});});}

  function selectedPurgeOptions(){var o={};$all('.bl-purge-check').forEach(function(c){o[c.value]=c.checked;});return o;}
  function setPurgeSource(source){purgeState.source=source;$all('.bl-tab').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-source')===source);});}
  function setPurgeButtons(hasIssues){$("#blPurgeApply").disabled=!hasIssues;$("#blPurgeSelectAll").disabled=!hasIssues;$("#blPurgeClearAll").disabled=!hasIssues;}
  function openPurge(){purgeState.issues=[];purgeState.lastReport="";purgeState.backupRows=[];purgeState.summaryRows=[];setPurgeButtons(false);$("#blPurgeDownloadExcel").disabled=true;$("#blPurgeResults").innerHTML='<div class="bl-empty">Aún no se ha analizado.</div>';resetProgress();$("#blPurgeModal").hidden=false;}
  function closePurge(){$("#blPurgeModal").hidden=true;}
  function docsFromRows(rows,source,storeOrCollection){return (rows||[]).map(function(row){var date=rowTime(row);return {source:source,store:source==="local"?storeOrCollection:"",collection:source==="firebase"?(row._collectionName||storeOrCollection):"",id:row._docId||idOf(row),data:row,score:completeness(row),updatedAtMs:date,updatedAtText:date?new Date(date).toISOString():"sin fecha"};});}
  function sortMostRecent(list){return list.slice().sort(function(a,b){if(b.updatedAtMs!==a.updatedAtMs){return b.updatedAtMs-a.updatedAtMs;}return b.score-a.score;});}
  function getRowsFor(source,type){if(type==="periodos"){return source==="firebase"?fireRows("periodos").then(function(r){return docsFromRows(r,source,"periodos");}):localRows("periodos").then(function(r){return docsFromRows(r,source,"periodos");});}return source==="firebase"?fireRows("Estudiantes").then(function(r){return docsFromRows(r,source,"Estudiantes");}):localRows("estudiantes_periodo_resumen").then(function(r){return docsFromRows(r,source,"estudiantes_periodo_resumen");});}
  function issue(id,tipo,title,severity,action,docs,details,fix){return {id:id,tipo:tipo,title:title,severity:severity,action:action,docs:docs||[],details:details||"",fix:fix||{}};}
  function analyzePeriods(source){return getRowsFor(source,"periodos").then(function(docs){var groups={},issues=[];docs.forEach(function(d){var n=window.BDLNormPeriodo?window.BDLNormPeriodo.normalize(d.data,d.id):{periodoId:periodOf(d.data,d.id),periodoLabel:periodLabel(d.id)};if(n.periodoId==="SIN_PERIODO"){issues.push(issue('periodo_sin_'+d.id,'periodos','Período sin formato válido','media','Marcar para revisión', [d], 'Documento sin período reconocible.', {canonical:n}));return;}if(!groups[n.periodoId])groups[n.periodoId]={canonical:n,docs:[]};groups[n.periodoId].docs.push(d);});Object.keys(groups).forEach(function(k){var g=groups[k];var bad=g.docs.filter(function(d){var raw=txt(d.id||d.data.periodoId||d.data.label||d.data.periodoLabel);var lab=txt(d.data.periodoLabel||d.data.label||d.data.nombre||"");return raw!==g.canonical.periodoId || (lab&&lab!==g.canonical.periodoLabel);});if(g.docs.length>1||bad.length){issues.push(issue('periodo_'+k,'periodos','Período duplicado o con formato diferente','alta','Crear período canónico y marcar formatos antiguos',g.docs,'Se unificará como: '+g.canonical.periodoLabel+'\nID interno: '+g.canonical.periodoId,{canonical:g.canonical}));}});return issues;});}
  function analyzeCedulas(source){return getRowsFor(source,"estudiantes").then(function(docs){var map={},issues=[];docs.forEach(function(d){var c=cedulaOf(d.data);if(c){(map[c]=map[c]||[]).push(d);}});Object.keys(map).forEach(function(c){if(map[c].length>1){var sorted=sortMostRecent(map[c]);var merged=mergeSmart(sorted[0],sorted);issues.push(issue('cedula_'+c,'cedulas','Cédula duplicada: '+c,'alta','Conservar registro más reciente, completar campos vacíos y marcar duplicados',sorted,'Registros encontrados: '+sorted.length+'\nPrincipal más reciente: '+nombreOf(sorted[0].data)+'\nFecha principal: '+sorted[0].updatedAtText+'\nCampos que se completarán desde otros registros si están vacíos.',{primaryId:sorted[0].id,cedula:c,primaryUpdatedAt:sorted[0].updatedAtText,merged:merged}));}});return issues;});}
  function analyzeTelefonos(source){return getRowsFor(source,"estudiantes").then(function(docs){var map={},issues=[];docs.forEach(function(d){var c=celularOf(d.data);if(c&&c.length>=7){(map[c]=map[c]||[]).push(d);}});Object.keys(map).forEach(function(c){var cedulas={};map[c].forEach(function(d){cedulas[cedulaOf(d.data)]=true;});if(map[c].length>1&&Object.keys(cedulas).length>1){issues.push(issue('telefono_'+c,'telefonos','Teléfono duplicado: '+c,'media','Marcar como conflicto para revisión manual',sortMostRecent(map[c]),'El mismo teléfono aparece en estudiantes distintos. No se fusiona ni se borra automáticamente.',{telefono:c}));}});return issues;});}
  function analyzeSinPeriodo(source){return getRowsFor(source,"estudiantes").then(function(docs){var bad=docs.filter(function(d){return periodOf(d.data,"")==="SIN_PERIODO";});return bad.length?[issue('sin_periodo','sinPeriodo','Estudiantes sin período claro','media','Marcar para revisión; no se asigna período automáticamente',bad,'Registros sin período reconocible: '+bad.length,{})]:[];});}
  function analyzeFormatos(source){return getRowsFor(source,"estudiantes").then(function(docs){var issues=[];docs.forEach(function(d){var ced=cedulaOf(d.data),per=periodOf(d.data,"");if(!ced||per==="SIN_PERIODO")return;var canon=canonicalId(d.data,per);if(d.id&&d.id!==canon){issues.push(issue('formato_'+d.id,'formatos','ID de documento no canónico','baja','Crear/actualizar documento canónico y marcar el anterior como formato antiguo',[d],'ID actual: '+d.id+'\nID correcto: '+canon,{canonicalId:canon}));}});return issues;});}
  function analyzePurge(){var source=purgeState.source, opts=selectedPurgeOptions(), tasks=[];out('Analizando depuración '+source+'...');purgeState.lastReport="";purgeState.backupRows=[];purgeState.summaryRows=[];$("#blPurgeDownloadExcel").disabled=true;setProgress(0,1,'Analizando incongruencias...');if(opts.periodos)tasks.push(analyzePeriods(source));if(opts.cedulas)tasks.push(analyzeCedulas(source));if(opts.telefonos)tasks.push(analyzeTelefonos(source));if(opts.sinPeriodo)tasks.push(analyzeSinPeriodo(source));if(opts.formatos)tasks.push(analyzeFormatos(source));return Promise.all(tasks).then(function(parts){purgeState.issues=[].concat.apply([],parts).slice(0,300);renderPurgeIssues();setProgress(1,1,'Análisis finalizado');out({fuente:source,incongruencias:purgeState.issues.length,reglaCedulas:'se conserva el registro más reciente y se completan vacíos'});return purgeState.issues;}).catch(function(e){setProgress(1,1,'Error en análisis');out({ok:false,error:e&&e.message?e.message:String(e)});});}
  function renderPurgeIssues(){var box=$("#blPurgeResults");if(!box)return;if(!purgeState.issues.length){box.innerHTML='<div class="bl-empty">No se encontraron incongruencias con las opciones seleccionadas.</div>';setPurgeButtons(false);return;}setPurgeButtons(true);box.innerHTML=purgeState.issues.map(function(i,idx){var docs=i.docs.slice(0,8).map(function(d){return '- '+(d.collection||d.store)+' / '+(d.id||'sin id')+' / '+nombreOf(d.data)+' / '+d.updatedAtText;}).join('\n');return '<article class="bl-issue"><div class="bl-issue-head"><div><div class="bl-issue-title">'+esc(i.title)+'</div><div class="bl-issue-meta">'+esc(i.action)+' · afectados: '+i.docs.length+'</div></div><span class="bl-severity '+esc(i.severity)+'">'+esc(i.severity)+'</span></div><div class="bl-issue-body">'+esc(i.details+'\n'+docs)+'</div><label><input type="checkbox" class="bl-issue-approve" data-issue="'+idx+'"> Aprobar esta corrección</label></article>';}).join('');}
  function setAllIssues(value){$all('.bl-issue-approve').forEach(function(c){c.checked=!!value;});out(value?'Todas las incongruencias quedaron aprobadas.':'Se quitó la selección de todas las incongruencias.');}
  function backupFirebase(issueObj,doc,action){var id='purga_'+Date.now()+'_'+Math.random().toString(36).slice(2);return fireSet('backup_purga',{fecha:now(),tipo:issueObj.tipo,accion:action,coleccion:doc.collection,docId:doc.id,before:doc.data,issue:issueObj.title},id).catch(function(){return null;});}
  function updateDoc(issueObj,doc,patch,storeOverride){var row=Object.assign({},doc.data||{},patch||{},{updatedAt:now()});if(doc.source==="firebase"){return backupFirebase(issueObj,doc,'update').then(function(){return fireSet(doc.collection||'Estudiantes',row,doc.id);});}return putLocal(storeOverride||doc.store,row);}
  function excelRowsForIssue(issueObj,status,error){return issueObj.docs.map(function(d,idx){return {fecha:now(),fuente:purgeState.source,tipo:issueObj.tipo,severidad:issueObj.severity,estado:status||'APROBADO',error:error||'',titulo:issueObj.title,accion:issueObj.action,principalSugerido:issueObj.fix.primaryId||'',criterio:'MAS_RECIENTE_CAMPOS_VACIOS_COMPLETADOS',orden:idx+1,coleccion:d.collection||d.store,documentoId:d.id||'',nombre:nombreOf(d.data),cedula:cedulaOf(d.data),celular:celularOf(d.data),periodo:periodOf(d.data,''),fechaRegistro:d.updatedAtText,datosAntes:js(d.data)};});}
  function applyIssue(issueObj){var p=Promise.resolve();if(issueObj.tipo==="periodos"){var c=issueObj.fix.canonical;if(issueObj.docs[0]&&issueObj.docs[0].source==="firebase"){p=p.then(function(){return fireSet('periodos',c,c.periodoId);});issueObj.docs.forEach(function(d){if(d.id!==c.periodoId){p=p.then(function(){return updateDoc(issueObj,d,{estadoDepuracion:'DUPLICADO_PERIODO',requiereRevision:true,periodoCanonicoId:c.periodoId,periodoCanonicoLabel:c.periodoLabel});});}});return p;}p=p.then(function(){return window.BDLRepoPeriodos&&window.BDLRepoPeriodos.guardar?window.BDLRepoPeriodos.guardar(c):putLocal('periodos',c);});issueObj.docs.forEach(function(d){if(d.id&&d.id!==c.periodoId&&window.BDLDB&&window.BDLDB.remove){p=p.then(function(){return window.BDLDB.remove('periodos',d.id).catch(function(){return null;});});}});return p;}
    if(issueObj.tipo==="cedulas"){var primary=issueObj.docs[0],merged=issueObj.fix.merged||mergeSmart(primary,issueObj.docs);p=p.then(function(){return primary.source==="firebase"?backupFirebase(issueObj,primary,'fusion principal').then(function(){return fireSet(primary.collection||'Estudiantes',merged,primary.id);}):putLocal(primary.store,merged);});issueObj.docs.slice(1).forEach(function(d){var patch={estadoDepuracion:'CEDULA_DUPLICADA',requiereRevision:true,estudiantePrincipalId:issueObj.fix.primaryId,cedulaDuplicada:issueObj.fix.cedula,criterioConservacion:'MAS_RECIENTE',fechaPrincipal:issueObj.fix.primaryUpdatedAt};p=p.then(function(){return updateDoc(issueObj,d,patch);});});return p;}
    if(issueObj.tipo==="telefonos"){issueObj.docs.forEach(function(d){p=p.then(function(){return updateDoc(issueObj,d,{estadoDepuracion:'TELEFONO_DUPLICADO_REVISION',requiereRevision:true,telefonoDuplicado:issueObj.fix.telefono});});});return p;}
    if(issueObj.tipo==="sinPeriodo"){issueObj.docs.forEach(function(d){p=p.then(function(){return updateDoc(issueObj,d,{estadoDepuracion:'SIN_PERIODO_REVISION',requiereRevision:true});});});return p;}
    if(issueObj.tipo==="formatos"){var d=issueObj.docs[0],canon=issueObj.fix.canonicalId;if(d.source==="firebase"){var clean=Object.assign({},d.data,{formatoCanonico:true,formatoCanonicoId:canon,idEstudiantePeriodo:canon});delete clean._docId;delete clean._collectionName;p=p.then(function(){return backupFirebase(issueObj,d,'crear canonico');}).then(function(){return fireSet(d.collection||'Estudiantes',clean,canon);}).then(function(){return updateDoc(issueObj,d,{estadoDepuracion:'FORMATO_ID_ANTIGUO',requiereRevision:true,formatoCanonicoId:canon});});return p;}var localClean=Object.assign({},d.data,{formatoCanonico:true,formatoCanonicoId:canon,idEstudiantePeriodo:canon});p=p.then(function(){return putLocal(d.store,localClean);}).then(function(){return updateDoc(issueObj,d,{estadoDepuracion:'FORMATO_ID_ANTIGUO',requiereRevision:true,formatoCanonicoId:canon});});return p;}
    return p;}
  function applyApproved(){var approved=$all('.bl-issue-approve:checked').map(function(c){return purgeState.issues[Number(c.getAttribute('data-issue'))];}).filter(Boolean);if(!approved.length){out('No hay correcciones aprobadas.');return;}$("#blPurgeApply").disabled=true;out('Corrigiendo seleccionados...');setProgress(0,approved.length,'Iniciando corrección...');var report={fuente:purgeState.source,aprobadas:approved.length,aplicadas:0,errores:0,fecha:now(),reglaCedulas:'Conservar registro más reciente y completar campos vacíos',detalle:[]};purgeState.backupRows=[];purgeState.summaryRows=[];var p=Promise.resolve();approved.forEach(function(i,idx){p=p.then(function(){setProgress(idx,approved.length,'Corrigiendo '+(idx+1)+' de '+approved.length+': '+i.title);return applyIssue(i).then(function(){report.aplicadas++;report.detalle.push({ok:true,tipo:i.tipo,titulo:i.title});purgeState.backupRows=purgeState.backupRows.concat(excelRowsForIssue(i,'CORREGIDO',''));setProgress(idx+1,approved.length,'Corregido '+(idx+1)+' de '+approved.length);}).catch(function(e){var msg=e&&e.message?e.message:String(e);report.errores++;report.detalle.push({ok:false,tipo:i.tipo,titulo:i.title,error:msg});purgeState.backupRows=purgeState.backupRows.concat(excelRowsForIssue(i,'ERROR',msg));setProgress(idx+1,approved.length,'Error registrado '+(idx+1)+' de '+approved.length);});});});return p.then(function(){purgeState.summaryRows=[{fecha:report.fecha,fuente:report.fuente,aprobadas:report.aprobadas,corregidas:report.aplicadas,errores:report.errores,reglaCedulas:report.reglaCedulas}];purgeState.lastReport=js(report);out(report);fill();counts();loadTable();$("#blPurgeDownloadExcel").disabled=false;setProgress(approved.length,approved.length,'Corrección finalizada');return downloadExcelReport(report).then(function(){return report;});});}
  function loadXlsx(){if(window.XLSX){return Promise.resolve(window.XLSX);}return new Promise(function(resolve,reject){var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=function(){window.XLSX?resolve(window.XLSX):reject(new Error('XLSX no disponible'));};s.onerror=function(){reject(new Error('No se pudo cargar XLSX'));};document.head.appendChild(s);});}
  function downloadBlob(blob,name){var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},800);}
  function downloadCsvFallback(name){var rows=purgeState.backupRows||[];var headers=Object.keys(rows[0]||{fecha:'',fuente:'',tipo:'',titulo:'',datosAntes:''});var csv=headers.join(';')+'\n'+rows.map(function(r){return headers.map(function(h){return '"'+txt(r[h]).replace(/"/g,'""')+'"';}).join(';');}).join('\n');downloadBlob(new Blob([csv],{type:'text/csv;charset=utf-8'}),name.replace('.xlsx','.csv'));}
  function downloadExcelReport(report){if(!purgeState.backupRows.length){out('No hay respaldo para descargar todavía.');return Promise.resolve(false);}var file='respaldo_purga_'+(purgeState.source||'datos')+'_'+new Date().toISOString().slice(0,19).replace(/[:T]/g,'-')+'.xlsx';return loadXlsx().then(function(XLSX){var wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(purgeState.summaryRows.length?purgeState.summaryRows:[report||{}]),'Resumen');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(purgeState.backupRows),'Respaldo');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet((purgeState.issues||[]).map(function(i){return {tipo:i.tipo,titulo:i.title,severidad:i.severity,accion:i.action,afectados:i.docs.length,detalle:i.details};})),'Incongruencias');var data=XLSX.write(wb,{bookType:'xlsx',type:'array'});downloadBlob(new Blob([data],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),file);return true;}).catch(function(){downloadCsvFallback(file);return false;});}
  function copyPurgeReport(){var text=purgeState.lastReport||js({issues:purgeState.issues});if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text);}out('Reporte copiado o listo para copiar.');}

  function search(){var q=norm($("#blSearch").value);var box=$("#blSearchResults");if(!q){box.innerHTML='<div class="bl-empty">Escriba un dato para buscar.</div>';return;}return allLocal().then(function(data){var found=[];Object.keys(data).forEach(function(store){(data[store]||[]).forEach(function(r){if(norm(js(r)).indexOf(q)>=0)found.push({store:store,row:r});});});found=found.slice(0,50);if(!found.length){box.innerHTML='<div class="bl-empty">No se encontró ningún dato.</div>';out({busqueda:q,resultados:0});return;}box.innerHTML=found.map(function(x,i){var n=nombreOf(x.row);return '<div class="bl-result"><div><strong>'+esc(n)+'</strong><br><small>BDLocal · '+esc(x.store)+'</small></div><button class="bl-btn light" data-found="'+i+'">Ver datos</button></div>';}).join('');$all('[data-found]').forEach(function(b){b.onclick=function(){var x=found[Number(b.getAttribute('data-found'))];openModal('Datos exactos · '+x.store,x.row);};});out({busqueda:q,resultados:found.length});});}
  function diag(){allLocal().then(function(d){var c={};Object.keys(d).forEach(function(k){c[k]=d[k].length;});out({fecha:now(),bdlocal:c,firebase:!!window.BDLSyncFirebase});});}
  function counts(){allLocal().then(function(d){var total=Object.keys(d).reduce(function(a,k){return a+d[k].length;},0);if($("#blCountLocal"))$("#blCountLocal").textContent=total;if($("#blCountFirebase"))$("#blCountFirebase").textContent=lastFirebase;if($("#blCountDiff"))$("#blCountDiff").textContent=lastDiff;localRows('sync_queue').then(function(q){if($("#blCountQueue"))$("#blCountQueue").textContent=q.length;});});}
  function openModal(t,d){$("#blModalTitle").textContent=t;$("#blModalBody").textContent=js(d);$("#blModal").hidden=false;}function closeModal(){$("#blModal").hidden=true;}
  function bind(){
    $("#blBtnLoadTable").onclick=loadTable;$("#blBtnDiff").onclick=compare;$("#blBtnSync").onclick=sync;$("#blBtnUpload").onclick=upload;$("#blBtnDownload").onclick=download;$("#blBtnPurge").onclick=openPurge;$("#blBtnSearch").onclick=search;$("#blSearch").onkeydown=function(e){if(e.key==='Enter')search();};$("#blBtnDiag").onclick=diag;$("#blModalClose").onclick=closeModal;
    $("#blPurgeClose").onclick=closePurge;$("#blPurgeAnalyze").onclick=analyzePurge;$("#blPurgeApply").onclick=applyApproved;$("#blPurgeCopy").onclick=copyPurgeReport;$("#blPurgeSelectAll").onclick=function(){setAllIssues(true);};$("#blPurgeClearAll").onclick=function(){setAllIssues(false);};$("#blPurgeDownloadExcel").onclick=function(){downloadExcelReport({manual:true,fecha:now()});};$all('.bl-tab').forEach(function(b){b.onclick=function(){setPurgeSource(b.getAttribute('data-source'));};});
  }
  function boot(){initStores();fill();bind();counts();out('BL listo.');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})(window,document);
