/* =========================================================
Nombre completo: diagnostico-runtime.js
Ruta o ubicación: /scripts/diagnostico-runtime.js
Función o funciones:
- Inspeccionar la aplicación Electron mediante DevTools remoto.
- Abrir BL, observar BL2App, IndexedDB, conectores y consola.
- Guardar un reporte sin ejecutar sincronizaciones externas.
========================================================= */
"use strict";
const fs=require("node:fs"),path=require("node:path");
const arg=(n,d)=>{const p=`--${n}=`;const v=process.argv.find(x=>String(x).startsWith(p));return v?String(v).slice(p.length):d;};
const port=Number(arg("port","9322")),seconds=Math.max(10,Number(arg("seconds","35"))),output=arg("output","artifacts/bdlocal-runtime.json");
const endpoint=`http://127.0.0.1:${port}/json/list`,wait=ms=>new Promise(r=>setTimeout(r,ms));
class CDP{
  constructor(url){this.url=url;this.ws=null;this.id=0;this.pending=new Map();this.events=[];}
  connect(){return new Promise((resolve,reject)=>{const ws=this.ws=new WebSocket(this.url),timer=setTimeout(()=>reject(new Error("DevTools no aceptó la conexión.")),10000);ws.addEventListener("open",()=>{clearTimeout(timer);resolve();});ws.addEventListener("error",()=>{clearTimeout(timer);reject(new Error("Falló el WebSocket de DevTools."));});ws.addEventListener("message",event=>{let m;try{m=JSON.parse(String(event.data));}catch{return;}if(m.id&&this.pending.has(m.id)){const p=this.pending.get(m.id);this.pending.delete(m.id);clearTimeout(p.timer);return m.error?p.reject(new Error(m.error.message||JSON.stringify(m.error))):p.resolve(m.result);}if(["Runtime.consoleAPICalled","Runtime.exceptionThrown","Log.entryAdded"].includes(m.method)){this.events.push({at:new Date().toISOString(),method:m.method,params:m.params||null});if(this.events.length>300)this.events.shift();}});});}
  send(method,params={}){return new Promise((resolve,reject)=>{const id=++this.id,timer=setTimeout(()=>{this.pending.delete(id);reject(new Error(`DevTools no respondió a ${method}.`));},12000);this.pending.set(id,{resolve,reject,timer});this.ws.send(JSON.stringify({id,method,params}));});}
  close(){try{this.ws.close();}catch{}}
}
const expression=String.raw`(async()=>{const t=v=>String(v==null?"":v).trim(),frames=Array.from(document.querySelectorAll("iframe"));let f=frames.find(n=>/[\\/]BDLocal[\\/]bl2\.html(?:$|[?#])/i.test(n.src||""));if(!f){const b=Array.from(document.querySelectorAll("button,a,[role='button']")).find(n=>t(n.textContent).toUpperCase()==="BL");if(b)try{b.click();}catch{}return{observedAt:new Date().toISOString(),bl:null,action:b?"Se pulsó BL.":"No se encontró BL.",frames:frames.map(n=>({id:n.id||"",src:n.src||""}))};}try{const w=f.contentWindow,d=f.contentDocument;let databases=[];try{if(w.indexedDB&&typeof w.indexedDB.databases==="function")databases=await w.indexedDB.databases();}catch(e){databases=[{error:e.message}];}return{observedAt:new Date().toISOString(),bl:{src:f.src||"",documentReadyState:d?d.readyState:"",dbPill:d&&d.getElementById("bl2-db-pill")?t(d.getElementById("bl2-db-pill").textContent):"",viewStatus:d&&d.getElementById("bl2-view-status")?t(d.getElementById("bl2-view-status").textContent):"",state:w.BL2App&&w.BL2App.getState?w.BL2App.getState():null,connectors:w.BDLocalConexiones&&w.BDLocalConexiones.status?w.BDLocalConexiones.status():null,dbMeta:w.BL2DB&&w.BL2DB.meta?w.BL2DB.meta():null,databases,logs:d?Array.from(d.querySelectorAll("#bl2-log .bl2-log-item")).slice(0,40).map(n=>t(n.innerText||n.textContent)):[],globals:{BL2App:!!w.BL2App,BL2DB:!!w.BL2DB,BL2Core:!!w.BL2Core,BL2Test:!!w.BL2Test,BDLocalConexiones:!!w.BDLocalConexiones,BDLSyncOutbox:!!w.BDLSyncOutbox,BDLSyncUIBridge:!!w.BDLSyncUIBridge,BDLocalConfigUI:!!w.BDLocalConfigUI}}};}catch(e){return{observedAt:new Date().toISOString(),bl:null,error:e.stack||e.message||String(e)};}})()`;
async function main(){const list=await (await fetch(endpoint)).json(),pages=list.filter(x=>x.type==="page"),target=pages.find(x=>/maq-index\.html/i.test(x.url||""))||pages[0];if(!target||!target.webSocketDebuggerUrl)throw new Error("No se encontró una página Electron inspeccionable.");const c=new CDP(target.webSocketDebuggerUrl);await c.connect();await c.send("Runtime.enable");await c.send("Log.enable").catch(()=>null);const snapshots=[],iterations=Math.ceil(seconds/2);for(let i=0;i<iterations;i++){const r=await c.send("Runtime.evaluate",{expression,awaitPromise:true,returnByValue:true}),s=r&&r.result&&Object.prototype.hasOwnProperty.call(r.result,"value")?r.result.value:{evaluationError:r&&r.exceptionDetails||r};snapshots.push(s);const b=s&&s.bl,st=b&&b.state;console.log(`[${i+1}/${iterations}] estado=${b?b.dbPill:"sin-BL"} ready=${st?st.ready:false} booting=${st?st.booting:false} scripts=${st?st.scriptsReady:false}`);await wait(2000);}fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify({ok:true,generatedAt:new Date().toISOString(),target:{id:target.id,title:target.title,url:target.url},snapshots,events:c.events},null,2),"utf8");c.close();}
main().catch(e=>{const report={ok:false,generatedAt:new Date().toISOString(),error:e.stack||e.message||String(e)};try{fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(report,null,2),"utf8");}catch{}console.error(report.error);process.exitCode=1;});
